### ISSUE TITLE
Validate enough Available memory instead of enough Free memory

### ISSUE THREAD

**Issue by cruscio** [confluentinc/cp-ansible#1014]
In a small cluster with both Zookeeper and Kafka on each node, an upgrade from 7.0 to 7.1 fails when there is sufficient _available_ RAM which happens to currently be used for cache (i.e. not _free_). It's okay, good even, for there to be very little _free_ RAM due to caching. Validating the _available_ RAM with `nocache.free` should allow the play to safely proceed.

Example ansible facts:

        "ansible_memfree_mb": 166,
        "ansible_memory_mb": {
            "nocache": {
                "free": 9170,
                "used": 6661
            },
            "real": {
                "free": 166,
                "total": 15831,
                "used": 15665
            },
            "swap": {
                "cached": 90,
                "free": 6216,
                "total": 7375,
                "used": 1159
            }

Proposed change to [confluent/platform/roles/common/tasks/host_validations.yml](https://github.com/confluentinc/cp-ansible/blob/7.1.0-post/roles/common/tasks/host_validations.yml):
`s/ansible_memfree_mb >/ansible_memory_mb.nocache.free >/g`

**Comment by erikgb** [comment]
Fixed by https://github.com/confluentinc/cp-ansible/pull/1030.
