### ISSUE TITLE
Improve JMX exporter performance by enabling cache

### ISSUE THREAD

**Issue by pantaoran** [confluentinc/cp-ansible#1023]
**Describe the issue**
This is a suggestion for a simple improvement that can bring a big performance boost to JMX exporter.
When a cluster has 1000+ topics, gathering the jmx metrics becomes quite slow. I have observed how the exporter took 30+ seconds to compute the metrics, but Prometheus only had a scrape interval of 30sec, so it was too slow.

Fortunately there is an optional feature in the jmx exporter which turns on a cache for "bean name expressions to rule computation (match and mismatch)". This simple toggle can improve the performance dramatically and should be used in your rules file. I do not see any downside to this.

**How to apply**
Here is the file where these changes should be made:
https://github.com/confluentinc/cp-ansible/blob/7.1.0-post/roles/kafka_broker/templates/kafka.yml.j2
For every rule you should add `cache: true` at the same level as `name` or `labels`.

**Expected improvement**
In my observation enabling the cache for all rules brought down metrics computation time from 30+ seconds to 2-4 seconds, which is a 10x improvement.

**Additional context**
My observations are based on Strimzi, not the Confluent Platform, but I believe that the jmx exporter should work the same in both contexts. 
I do not have the capacity to test it with CP, which is why I'm not opening a pull request.

**Comment by erikgb** [comment]
I am positive to this. Just some words of caution from the JMX exporter docs:

> Whether to cache bean name expressions to rule computation (match and mismatch). Not recommended for rules matching on bean value, as only the value from the first scrape will be cached and re-used. This can increase performance when collecting a lot of mbeans. Defaults to false.

I am not sure if I totally understand the limitations to this.

**Comment by utkarsh5474** [comment]
We have added a new variable to give users the flexibility to turn cache to true (default value being false)

**Comment by gadelkareem** [comment]
I am not sure if this var clears the confusion still. All cache on the broker have this variable for the cache. Will enabling it cache old values still? Or is there a way to set the cache lifecycle?
