### ISSUE TITLE
Add licence for Control Center

### ISSUE THREAD

**Issue by lduparc** [confluentinc/cp-ansible#106]
Where can I update the configuration to add a licence for confluent-control-center  ?

**Comment by jvalderrama** [comment]
Hi @lduparc  , you can add the license configuration in control-center file **control-center-production.properties**  located at /etc/confluent-control-center/control-center-production.properties with the key **confluent.controlcenter.license=xxxx**

**Comment by lduparc** [comment]
Thanks
