### ISSUE TITLE
Systemd Dependencies - Kafka after Zookeeper, Schema Registry after Kafka, ...

### ISSUE THREAD

**Issue by baunz** [confluentinc/cp-ansible#109]
Hi,

currently when rebooting an one server installation we run into problems - I suspect it might be a problem that they all start independently, getting something like 

```` 
ERROR Error starting the schema registry (io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication)
io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryInitializationException: Error initializing kafka store while initializing schema registry
````

in the schema registry log while the kafka server is still booting at that time. Do you consider this also a problem and would a systemd "After" definitition fix this?

Thanks a lot for your time,

Johannes

**Comment by JumaX** [comment]
Hello Johannes,

Thank you for the question.  It's possible that using 'after' in systemd scripts could resolve this if you are running all on one host.  We haven't specifically tested this, as generally speaking you will want to install across multiple hosts, and restart in a rolling fashion.

Thanks

**Comment by baunz** [comment]
Hi and thanks for the reply. We are using the one-host setup only for our test environment. Maybe we will investigate further into this and provide a pull request, but for now this issue can be closed since the single node setup is not the main focus of the playbooks I think.

Cheers,
Johannes
