### ISSUE TITLE
Where to find the 5.5.9 version?

### ISSUE THREAD

**Issue by VolodymyrLenyk** [confluentinc/cp-ansible#1111]
**Describe the issue**
There is no 5.5.9-post branch of Kafka in the repo. How can I navigate to the version of Kafka representing the https://docs.confluent.io/5.5.9/release-notes/changelog.html#version-5-5-9 version?

**Comment by utkarsh5474** [comment]
Hi, we have stopped releasing new patches of 5.5.x
We'd want all our customers to move to the newer cp versions. 
In case you want to use 5.5.9, you can change this - https://github.com/confluentinc/cp-ansible/blob/5.5.8-post/roles/confluent.variables_handlers/defaults/main.yml#L6 to 5.5.9 on branch 5.5.8-post.
