### ISSUE TITLE
Referencing debian sid distribution

### ISSUE THREAD

**Issue by reneveyj** [confluentinc/cp-ansible#1136]
https://github.com/confluentinc/cp-ansible/blob/8de49f4c6a95b491156164e4eb7bf4cd80c6da1e/roles/common/tasks/debian.yml#L120

Adding sid to the sources.list of the host could cause it to update to vulnerable packages without sys admins noticing it. This should be fixed as soon as possible.

**Comment by utkarsh5474** [comment]
Hey,
Thanks for bringing this up.
This has been disabled by default in the latest cp-ansible patch. Ref https://github.com/confluentinc/cp-ansible/pull/1158
