### ISSUE TITLE
Setting up confluent kafka in air-gap installation

### ISSUE THREAD

**Issue by ishantanu** [confluentinc/cp-ansible#115]
Hi,

I wanted to use this playbook for setting up kafka on air-gap installation. But, the issue is that the target systems do not have direct access to the internet. So, how do I manage this? How can I get the clone of yum repo locally and then allow the playbook to pick the components on the OS itself instead of downloading from the internet?

**Comment by soenkeliebau** [comment]
Hi @ishantanu 
for making a copy of the repository check out the [yum downloadonly module](https://www.thegeekdiary.com/how-to-use-yum-downloadonly-to-download-a-package-without-installing-it/) and [createrepo](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-yum_repository). 
Those two enable creating a local mirror with the necessary packages, which you can then serve with a webserver of your choice (I've used python SimpleHTTPServer in the past, which works well enough if you don't provision too many servers at once).

Then you override the confluent.repository.redhat.dist.baseurl variable with the link to that repo and maybe disable gpg checking and you should be good to go.

This was Redhat specific, for Debian I think the apt-get command has a -d parameter that downloads and the equivalent to createrepo seems to be dpkg-scanpackages - but I have never used that.

**Comment by ishantanu** [comment]
Thanks for the response @soenkeliebau. This will help.
