### ISSUE TITLE
confluent.ssl.keystore.location unknwon parameter 

### ISSUE THREAD

**Issue by bcondeQuod** [confluentinc/cp-ansible#1193]
Hello all,
On cp-ansible/roles/variables/vars/main.yml I have a section in kafka_broker_properties -> sr_ssl :
`sr_ssl:
    properties:
      confluent.ssl.truststore.location: "{{kafka_broker_truststore_path}}"
      confluent.ssl.truststore.password: "{{kafka_broker_truststore_storepass}}"
      confluent.ssl.keystore.location: "{{kafka_broker_keystore_path}}"
      confluent.ssl.keystore.password: "{{kafka_broker_keystore_storepass}}"
      confluent.ssl.key.password: "{{kafka_broker_keystore_keypass}}"
`
However I didn't see confluent.ssl.truststore.location on the official documentation , they talked about ssl.truststore.location. Do we have a module or a filter that remove the confluent prefix in the playbooks ? 
Thanks

**Comment by utkarsh5474** [comment]
Hi, No, we don't have a module/filter that is removing the confluent prefix. 
We had a look and as you suggested, we can't find this property in the official doc. So, we have removed it from the property list.
