### ISSUE TITLE
JMX broker performance improvement

### ISSUE THREAD

**Issue by gadelkareem** [confluentinc/cp-ansible#1242]
**Describe the issue**

<details>
<summary> I am running 3 Standard_DS3_v2 brokers  vms on Azure.</summary>

| Size | vCPU | Memory: GiB | Temp storage (SSD) GiB | Max data disks | Max cached and temp storage throughput: IOPS/MBps (cache size in GiB) | Max uncached disk throughput: IOPS/MBps | Max NICs | Expected network bandwidth (Mbps) |
| -- | -- | -- | -- | -- | -- | -- | -- | -- |
| Standard_DS3_v2 | 4 | 14 | 28 | 16 | 16000/128 (172) | 12800/192 | 4 | 3000 |

</details>

But the performance of broker JMX metrics need some improvements.

`jmx_scrape_duration_seconds 16.239545758`

This could be solved either by enabling cache or adding a whitelist to the config.  However, both solution are troublesome:
1. [Enabling `kafka_broker_jmxexporter_bean_name_expressions_cache: true`](https://github.com/confluentinc/cp-ansible/pull/1045) will result in reporting cached values.
2. Adding `whitelistObjectNames` to `kafka.yml.j2` will need to sacrifice a lot of metrics which I need to display in Grafana.

**Environment:**
 - OS: el7.x86_64
 - CP-Ansible Branch: 7.3.0
 - Ansible Version ansible 2.9.6

**Comment by nsharma-git** [comment]
@gadelkareem Can you please let us know whats the expectation from Ansible on this
