### ISSUE TITLE
Upgrade with Galaxy Module fails when new confluent archive is not present

### ISSUE THREAD

**Issue by rathberm** [confluentinc/cp-ansible#1243]
**Describe the issue**
When upgrading our Zookeeper nodes using the Ansible Galaxy Module v7.2.2 and the "installation_method: archive", the playbook fails at the [Task Get Leader/Follower](https://github.com/confluentinc/cp-ansible/blob/f8766f3252a03d026d054df24474569ab0117985/roles/zookeeper/tasks/dynamic_groups.yml#L28) with the following Error:
```
"cmd": "set -o pipefail &&\n  /opt/apps/confluent/confluent-7.2.2/bin/kafka-run-class  org.apache.zookeeper.client.FourLetterWordMain host.domain.com 2181 srvr  | grep Mode\n",
"stderr": "/bin/bash: line 1: /opt/apps/confluent/confluent-7.2.2/bin/kafka-run-class: No such file or directory"
```
It seems that the "zookeeper_health_check_command" inside the Task is using the Variable "binary_base_path", which is set to the Confluent Platform Version we want to upgrade to. But the new Version of the Confluent Archive is not yet present on the hosts, since the copy of the archive happens later during the playbook. 
As a workaround we stopped the Zookeeper service on the hosts since then no health check is performed and the playbook behaves as expected. With this workaround it's not possible to update our production environment, since we would like to perform the update in a rolling manner without downtime.

**To Reproduce**
Try to update zookeeper to a new version while the service is running, with the new confluent version archive not yet available on the target hosts.

**Expected behaviour**
We expect the health check to happen only after copying the archive to the hosts or the check should use an older version of the executables.  

**Inventory File**
Please provide your inventory file in order to aid in the investigation.

**Logs**
(fatal: [host.domain.com]: FAILED! => {"changed": false, "cmd": "set -o pipefail &&\n  /opt/apps/confluent/confluent-7.2.2/bin/kafka-run-class  org.apache.zookeeper.client.FourLetterWordMain host.domain.com 2181 srvr  | grep Mode\n", "delta": "0:00:00.003179", "end": "2022-11-08 11:21:47.392448", "msg": "non-zero return code", "rc": 1, "start": "2022-11-08 11:21:47.389269", "stderr": "/bin/bash: line 1: /opt/apps/confluent/confluent-7.2.2/bin/kafka-run-class: No such file or directory", "stderr_lines": ["/bin/bash: line 1: /opt/apps/confluent/confluent-7.2.2/bin/kafka-run-class: No such file or directory"], "stdout": "", "stdout_lines": []})

**Environment (please complete the following information):**
 - OS: SLES 12 SP5
 - Galaxy Module: confluent.platform 7.2.2
 - Ansible Version: ansible 2.12.0

**Comment by utkarsh5474** [comment]
Hi, What was your starting version? Are you doing a rolling upgrade?
Also, can you run the playbooks in verbose mode (-vvvv) and share the output of task https://github.com/confluentinc/cp-ansible/blob/f8766f3252a03d026d054df24474569ab0117985/roles/zookeeper/tasks/dynamic_groups.yml#L14 and the task above this one (Load override.conf)
zookeeper_current_version is actually used to resolve the correct binary_base_path, so I want to see what it is evaluating to

**Comment by rathberm** [comment]
Hello @utkarsh5474 ,
the starting version is 6.2.0. As you can see below, zookeeper_current_version is set correctly to 6.2.0, the health check still uses the wrong version.
```
TASK [confluent.platform.zookeeper : Set zookeeper_current_version variable - Archive Installer] ****************************************************************************
task path: /home/USER/.ansible/collections/ansible_collections/confluent/platform/roles/zookeeper/tasks/dynamic_groups.yml:14
ok: [HOST1] => {
    "ansible_facts": {
        "zookeeper_current_version": "6.2.0"
    },
    "changed": false
}
ok: [HOST2] => {
    "ansible_facts": {
        "zookeeper_current_version": "6.2.0"
    },
    "changed": false
}
ok: [HOST3] => {
    "ansible_facts": {
        "zookeeper_current_version": "6.2.0"
    },
    "changed": false
}
```

**Comment by omersiar** [comment]
Hi,

When upgrading, documentation says checkout to targeted branch,
this sets `binary_base_path` to https://github.com/confluentinc/cp-ansible/blob/6.2.7-post/roles/confluent.variables/vars/main.yml#L14
also `confluent_package_version` becomes to checked-out version
https://github.com/confluentinc/cp-ansible/blob/6.2.7-post/roles/confluent.variables/defaults/main.yml#L5

"Get Leader/Follower" task https://github.com/confluentinc/cp-ansible/blob/6.2.7-post/roles/confluent.zookeeper/tasks/dynamic_groups.yml#L24 depends on `zookeeper_health_check_command`
which does not use previously set fact `zookeeper_current_version` but instead `binary_base_path`
hence the error arise

"Get Leader/Follower" task find another way to set base path for the binary.

**Comment by omersiar** [comment]
> Hi, What was your starting version? Also, can you run the playbooks in verbose mode (-vvvv) and share the output of task
> 
> https://github.com/confluentinc/cp-ansible/blob/f8766f3252a03d026d054df24474569ab0117985/roles/zookeeper/tasks/dynamic_groups.yml#L14
> 
> and the task above this one (Load override.conf)
> zookeeper_current_version is actually used to resolve the correct binary_base_path, so I want to see what it is evaluating to


```
TASK [confluent.zookeeper : Set zookeeper_current_version variable - Archive Installer] ****************************************************************************************************************************************************
task path: /root/ansible/cp-ansible/roles/confluent.zookeeper/tasks/dynamic_groups.yml:12
Monday 28 November 2022  13:25:43 +0300 (0:00:00.544)       0:00:07.432 *******
ok: [hostname] => {"ansible_facts": {"zookeeper_current_version": "6.2.1"}, "changed": false}
```

```
TASK [confluent.zookeeper : Load override.conf - Archive Installer] ************************************************************************************************************************************************************************
task path: /root/ansible/cp-ansible/roles/confluent.zookeeper/tasks/dynamic_groups.yml:6
Monday 28 November 2022  13:25:43 +0300 (0:00:00.991)       0:00:06.887 *******
ok: [host] => {"changed": false, "content": "W1NlcnZpY2VdCiMgSWYgdGhlcmUgaXMgYW4gRXhlY1N0YXJ0IG92ZXJyaWRlIHRoZW4gd2UgbmVlZCB0byBjbGVhciB0aGUgRXhlY1N0YXJ0IGxpc3QgZmlyc3QKRXhlY1N0YXJ0PQpFeGVjU3RhcnQ9L29wdC9jb25mbHVlbnQvY29uZmx1ZW50LTYuMi4xL2Jpbi96b29rZWVwZXItc2VydmVyLXN0YXJ0IC9vcHQvY29uZmx1ZW50L2V0Yy9rYWZrYS96b29rZWVwZXIucHJvcGVydGllcwpFbnZpcm9ubWVudD0iS0FGS0FfSEVBUF9PUFRTPS1YbXgxZyIKRW52aXJvbm1lbnQ9IktBRktBX09QVFM9LURqZGsudGxzLmVwaGVtZXJhbERIS2V5U2l6ZT0yMDQ4IC1qYXZhYWdlbnQ6L29wdC9wcm9tZXRoZXVzL2pteF9wcm9tZXRoZXVzX2phdmFhZ2VudC5qYXI9ODA3OTovb3B0L3Byb21ldGhldXMvem9va2VlcGVyLnltbCIKRW52aXJvbm1lbnQ9IktBRktBX0xPRzRKX09QVFM9LURsb2c0ai5jb25maWd1cmF0aW9uPWZpbGU6L29wdC9jb25mbHVlbnQvZXRjL2thZmthL3pvb2tlZXBlci1sb2c0ai5wcm9wZXJ0aWVzIgpFbnZpcm9ubWVudD0iTE9HX0RJUj0vdmFyL2xvZy9rYWZrYSIK", "encoding": "base64", "source": "/etc/systemd/system/confluent-zookeeper.service.d/override.conf"}
```

Decoded base64
```
[Service]
# If there is an ExecStart override then we need to clear the ExecStart list first
ExecStart=
ExecStart=/opt/confluent/confluent-6.2.1/bin/zookeeper-server-start /opt/confluent/etc/kafka/zookeeper.properties
Environment="KAFKA_HEAP_OPTS=-Xmx1g"
Environment="KAFKA_OPTS=-Djdk.tls.ephemeralDHKeySize=2048 -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=8079:/opt/prometheus/zookeeper.yml"
Environment="KAFKA_LOG4J_OPTS=-Dlog4j.configuration=file:/opt/confluent/etc/kafka/zookeeper-log4j.properties"
Environment="LOG_DIR=/var/log/kafka"
```

**Comment by omersiar** [comment]
Notice `zookeeper_current_version` is never used.

**Comment by omersiar** [comment]
Changing line
https://github.com/confluentinc/cp-ansible/blob/6.2.7-post/roles/confluent.variables/defaults/main.yml#L320
to
```
zookeeper_health_check_command: "{{ ((config_base_path,('confluent-',zookeeper_current_version) | join) | community.general.path_join) }}/bin/kafka-run-class
```
worked for me

**Comment by omersiar** [comment]
Also this is an issue for kafka_broker as well,

Changing line
https://github.com/confluentinc/cp-ansible/blob/6.2.7-post/roles/confluent.kafka_broker/tasks/dynamic_groups.yml#L44
to

```
      {{ ((config_base_path,('confluent-',kafka_broker_current_version) | join) | community.general.path_join) }}/bin/zookeeper-shell {{ hostvars[groups['zookeeper'][0]] | resolve_hostname }}:{{ zookeeper_client_port }}{{zookeeper_chroot}}
```
worked for me

**Comment by utkarsh5474** [comment]
Thanks a lot @omersiar.
I have raised a PR to fix this.
