### ISSUE TITLE
Not possible to upgrade kafka_connect Plugins

### ISSUE THREAD

**Issue by rathberm** [confluentinc/cp-ansible#1244]
**Describe the issue**
Similar to #757, we noticed that when using the parameter "kafka_connect_plugins_remote" in our inventory file to install connect plugins it's not possible to update them by simply changing the version of the binary in the name of the plugin. When the version of a plugin is changed, it is handled the same way a new plugin is handled and a new folder with the plugin name as name is created. This can result in multiple versions of the same plugin and a situation where it is unclear which plugin version is currently used by Kafka Connect.
We think the easiest solution for this would be to clean the plugin directory at startup [here](https://github.com/confluentinc/cp-ansible/blob/7.3.0-post/roles/kafka_connect/tasks/connect_plugins.yml) and download the plugins new every time. If you are interested in such a solution, we would implement it and create a PR,

**To Reproduce**
Change the version of a plugin binary by changing its name in "kafka_connect_plugins_remote" inside the inventory file and redeploy  Kafka Connect.

**Expected behaviour**
The older plugin version should be removed before Connect startup.

**Environment (please complete the following information):**
 - OS: SLES 12 SP 5
 - Galaxy Module: confluent.platform 7.3.0
 - Ansible Version: ansible 2.13.4

**Comment by wadhwa1** [comment]
We'll use confluent-hub cli for installing local and remote plugins (Reference - https://docs.confluent.io/kafka-connectors/self-managed/confluent-hub/client.html#installing-while-offline-using-a-zip-file)
Confluent-hub CLI takes care of upgrading and downgrading the plugin very nicely.

In earlier/ existing approach, multiple folders of same kafka connect plugin used to get created in {{kafka_connect_plugins_dest}} /usr/share/java -
`confluentinc-kafka-connect-s3-10.2.4` directory containing v10.2.4 (installed by unarchiving the zip)
`confluentinc-kafka-connect-s3-10.3.0` directory containing v10.3.0 (installed by unarchiving the zip)
This can result into ambiguity.

But now with confluent-hub CLI approach, we’ll always have single folder of connect plugin.
Attaching the screenshot -
<img width="1728" alt="1244" src="https://user-images.githubusercontent.com/62242771/210769427-2fba3454-1038-48e8-9680-9b5fd23095b6.png">



For handling upgrades, we are updating the default kafka connect plugins path to /usr/share/java/connect_plugins
which means, now onwards, all connect plugins (local, remote, confluent-hub) will reside in new location /usr/share/java/connect_plugins
