### ISSUE TITLE
Different actions taken for platform installation on Redhat & Debian 

### ISSUE THREAD

**Issue by soenkeliebau** [confluentinc/cp-ansible#125]
Currently the Confluent platform installation task is implemented differently depending on whether it is executed on a Debian or Redhat system.

For Redhat the state is specified as "[latest](https://github.com/confluentinc/cp-ansible/blob/5.3.0-post/roles/confluent.common/tasks/redhat.yml#L25)", so existing Confluent Platform installations would be upgraded when running the playbooks.
For Debian nothing is specified, so this will default to "[present](https://docs.ansible.com/ansible/latest/modules/apt_module.html)" meaning no upgrade will take place.

As the official stance currently is that the playbooks don't support upgrading I think this should be changed in the Redhat task.

**Comment by JumaX** [comment]
@soenkeliebau  Thanks for the feedback.  The original intent was that you wanted to install the latest version, on a new cluster.  In the release we have coming out shortly, it's configurable as to which version you wish to install.

**Comment by akamensky** [comment]
1 - I don't think it is an enhancement, more like a bug. Actually quite serious one, considering that this does not implement idempotence, which can break existing installation by upgrading it.
2 - PR #126 was sent like a month ago, but never merged and now has conflicts, meantime the RHEL versions are still going to be upgraded without asking.

**Comment by JumaX** [comment]
@soenkeliebau @akamensky We have just pushed a new release which correct this behaviour.  It's now marked as `present` as opposed to `latest`.
