### ISSUE TITLE
Hardcoded broker config files

### ISSUE THREAD

**Issue by soenkeliebau** [confluentinc/cp-ansible#127]
The broker config files have a lot of hardcoded values that are not changeable (for example location of keystores and truststores, keystore password etc.) which makes them unusable for production deployments.
These also cannot be overridden by adding variables to the hosts kafka.config dictionary, as this is parsed before the hardcoded values and thus in turn overridden again.

An easy fix would be to make the used template a variable that users can override, but I wanted to double check whether there are other plans around how this can become more dynamic before creating a pull request.

**Comment by JumaX** [comment]
Hi @soenkeliebau we have a big release due any day which will make almost all configuration variables overridable.  Stay tuned.

**Comment by JumaX** [comment]
@soenkeliebau we just merged the following PR which should resolve a lot of the hardcoding, if not all of it.  Almost everything should be overridable now.

https://github.com/confluentinc/cp-ansible/pull/124
