### ISSUE TITLE
How can I Adding s3 Connector?

### ISSUE THREAD

**Issue by bohblue2** [confluentinc/cp-ansible#128]
I don't know where to start.

**Comment by soenkeliebau** [comment]
Hi @bohblue2 , the question as it currently stands is a bit too broad to really answer. 
Can you be a bit more specific about what you want to achieve please?

**Comment by bohblue2** [comment]
@soenkeliebau I've cp-ansible 5.3.0 installed on my aws and trying to install s3 connector modifying existing ansible script(https://github.com/confluentinc/cp-ansible/tree/5.3.0-post/roles/confluent.connect-distributed/tasks). but I would like to know a better way than implementing all ansible script that installing s3 connector and setting up all configuration to make a connection with s3.

**Comment by cricket007** [comment]
S3 Connect is included with Confluent Platform. There sholuld be nothing more for you to do to install it. 

You will have to POST your own Connect worker properties for sending data to S3; Ansible does not manage that. 

https://docs.confluent.io/current/connect/references/restapi.html
https://docs.confluent.io/current/connect/kafka-connect-s3/configuration_options.html#s3-configuration-options

**Comment by bohblue2** [comment]
@cricket007 Thanks it helps me a lot
