### ISSUE TITLE
Kerberos krb5.conf

### ISSUE THREAD

**Issue by evilezh** [confluentinc/cp-ansible#129]
It would be nice, if krb5.conf would be optional.
On servers quite often krb5.conf is already pre-configured as part of server enrollment.

**Comment by JumaX** [comment]
@evilezh Thanks for the feedback.  We are shipping a new release in the next day or two which will greatly enhance what can be configured/specified in the configs.  Stay tuned.

**Comment by JumaX** [comment]
@evilezh We have shipped the 5.3.0 release which allows you to override most configs.  We have also just shipped another release, which provides better settings for kerberos out of the box, as some of our default settings were using deprecated encryption times.  I would advise you to try the latest release.
