### ISSUE TITLE
Deploy Kafka without zookeeper

### ISSUE THREAD

**Issue by proffust** [confluentinc/cp-ansible#1297]
according with https://issues.apache.org/jira/browse/KAFKA-9119 Kafka support deployment without zookeeper, but role not support this.

**Comment by suikast42** [comment]
[Kip-500 i](https://issues.apache.org/jira/browse/KAFKA-14370?jql=labels%20%3D%20kip-500)s not productive as I know.

**Comment by nsharma-git** [comment]
Ansible will support new cluster deployment without zookeeper from 7.4 release ( Q1 2023). However, upgrading from zookeeper based cluster to non-zookeeper would not be possible yet.

**Comment by OneCricketeer** [comment]
7.4 is released now. https://www.confluent.io/blog/introducing-confluent-platform-7-4/

Any updates?
