### ISSUE TITLE
Kafka without Zookeeper

### ISSUE THREAD

**Issue by kkotowick** [confluentinc/cp-ansible#130]
I've read in multiple places that Kafka now supports clustering without use of Zookeeper. Is it possible to install a Kafka cluster without Zookeeper using this Ansible library?

**Comment by JumaX** [comment]
Hello @kkotowick, it's actually not possible to run kafka without zookeeper under any official distribution at this time.  Their are a few experiments I've read about, but nothing supported by the Apache kafka project itself.

**Comment by hden** [comment]
For those who stumble upon this thread, there is an active JIRA ticket for this: [KIP-500: Replace ZooKeeper with a Metadata Quorum](https://issues.apache.org/jira/browse/KAFKA-9119).
