### ISSUE TITLE
Can I use this code in cp-ansible for Debian 11 version(ansible_distribution=bullseye))?

### ISSUE THREAD

**Issue by ramyanarsupalli2109** [confluentinc/cp-ansible#1320]
Hello, 
I have used the collection confluent/platform and I see the host_validation file where I can only use the debian versions 9 and 10. Isn't it possible to use the roles for Debian 11 version?

Please recommend if this repo (https://github.com/confluentinc/cp-ansible) can be used for Debian 11 version.

**Comment by utkarsh5474** [comment]
Hey, 
Debian 11 is not supported by Confluent yet. Refer [this](https://docs.confluent.io/platform/current/installation/versions-interoperability.html#operating-systems)
And, that's why we have this validation. 

If you still want to try running on Debian11, you can use
`ansible-playbook .... --skip-tags 'validate_os_version'`
However, we haven't tested the playbooks with debian11 and more importantly, it's not supported by CP. So, things might not work.

**Comment by ramyanarsupalli2109** [comment]
Hi,
Yes, I tried by skipping the  tags 'validate_os_version' and replaced 'buster' with 'bullseye'. The kafka-broker  nodes and the zookeeper nodes were running fine(services are running and the proper configurations are in-place). I have also done a basic test by sending messages after creation of topic using 
kafka-console-producer --broker-list server1:9092, server2:9092, server3:9092 
and  I see the messages are being consumed  via the command   
kafka-console-consumer --bootstrap-server  server1:9092,server2:9092,server3:9092 --topic testing --from-beginning

According to above tests, Can I  continue with installation of confluent role on Debian 11 or should I consider any other important aspects(If I am missing something)?

Also I see the client packages provided by confluent doesn't have bullseye in Debian distributions.
(https://packages.confluent.io/clients/deb/dists/). Is it really a requirement that the client packages needs to be installed on Kafka-Cluster? I think only the clients which needs to interact with Kafka-Cluster generally need these packages. Can't these packages on clients be installed by means of any other alternative?

**Comment by utkarsh5474** [comment]
> Is it really a requirement that the client packages needs to be installed on Kafka-Cluster? I think only the clients which needs to interact with Kafka-Cluster generally need these packages. Can't these packages on clients be installed by means of any other alternative?
With my limited understanding, shouldn't be required. For details, you can have a look at Confluent docs. Here's a little something I can find - https://docs.confluent.io/platform/current/installation/installing_cp/deb-ubuntu.html#get-the-software

> According to above tests, Can I continue with installation of confluent role on Debian 11 or should I consider any other important aspects(If I am missing something)?
We (CP or CP-Ansible) don't officially support Debian11. If things look fine (and by these tests, they do), you can go ahead by all means. 
Though, I'll highly suggest using a supported OS as we won't be able to help you with any problems you encounter with Debian11.

**Comment by rnarsupalli-transporeon** [comment]
Thanks for your inputs.
