### ISSUE TITLE
Update confluent_package_version to 7.3.2

### ISSUE THREAD

**Issue by dainesj** [confluentinc/cp-ansible#1325]
**For Confluent Enterprise Support customers, we would strongly advise you to open a Support ticket which will be addressed within your Support contract SLA at ```https://support.confluent.io```**

**Describe the issue**
The default confluent_package_version pulls the 7.3.1 CP versions.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Inventory File**
Please provide your inventory file in order to aid in the investigation.

**Logs**
Please provide the output of the ```-vvv``` switch from Ansible with the failed log snippet. Please also provide the logs of the specific component which has failed.  If multiple attempts to run have been made, please provide the start and stop time of the component if known.

**Environment (please complete the following information):**
 - OS: Any
 - CP-Ansible Branch: 7.3.2-post
 - Ansible Version : Any

**Additional context**

**Comment by utkarsh5474** [comment]
Hi @dainesj 
CP 7.3.2 is not out yet. 
CP-Ansible had a bit of divergence from the CP versioning, to accommodate for hotfixes. There's a doc detailing the same on the internal slack. 
So, CP-Ansible 7.3.2-post is going to install latest CP version 7.3.1
Mapping between cp-ansible branch and cp version can also be found here - https://docs.confluent.io/ansible/current/ansible-requirements.html#general-requirements
