### ISSUE TITLE
Only one of inter.broker.listener.name and security.inter.broker.protocol should be set.

### ISSUE THREAD

**Issue by rnarsupalli-transporeon** [confluentinc/cp-ansible#1327]
Hello Team,
I have the below issue.
Can't I set both properties  , inter.broker.listener.name and security.inter.broker.protocol in my server.properties of my kafka-broker when setting sasl.mechanism=PLAIN for testing?
I am trying to use inter.broker.listener.name: BROKER and ecurity.inter.broker.protocol: SASL_PLAINTEXT, and I face the issue 
Only one of inter.broker.listener.name and security.inter.broker.protocol should be set.
In this case how can I implement the security?
when I remove it and try to send messages via producer I face this issue:
when I remove it , I get the following issue when I try to connect using producer 
ERROR [Producer clientId=console-producer] Connection to node -1 (localhost/127.0.0.1:9092) failed authentication due to: Unexpected handshake request with client mechanism PLAIN, enabled mechanisms are [] (org.apache.kafka.clients.NetworkClient)
WARN [Producer clientId=console-producer] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient

How to fix this issue?

**Comment by utkarsh5474** [comment]
Hi, 
This seems more to do with Kafka broker configurations. If you're adding a custom property, you'll have to check the docs on how/what it does. We won't be the best people to help you with this.

If you want to enable SASL using cp-ansible, you can have a look here - https://docs.confluent.io/ansible/current/ansible-authenticate.html#ak-authentication
