### ISSUE TITLE
How to generate ssl certificates with confluent.ssl role

### ISSUE THREAD

**Issue by suddy417** [confluentinc/cp-ansible#1330]
Hello 

what’s the correct way to use the ssl role provided in order to generate the ssl certificates ?

I have tried using ssl.enabled=true

but I couldn’t see any certificates gets generated.

it just fails by looking for certificates

could you please help me in setting the variables which helps me generating the certificates 

Thank you in advance

**Comment by utkarsh5474** [comment]
https://docs.confluent.io/ansible/current/ansible-install.html#install-individual-cp-components
As per the docs,
Generate the certificate authority (CA) if TLS encryption is enabled and using self-signed certificates.
`ansible-playbook -i hosts.yml confluent.platform.all --tags=certificate_authority`

So, if you have `ssl_enabled: true` in your inventory file and want to use self signed certificates, then you just need to run the command mentioned above and then continue with other components. 

If you want to provide custom certs or keystores, pls have a look here - https://docs.confluent.io/ansible/current/ansible-encrypt.html#certificates

**Comment by suddy417** [comment]
Okay thanks
