### ISSUE TITLE
Is SCRAM-SHA 512 is supported ? In this role

### ISSUE THREAD

**Issue by suddy417** [confluentinc/cp-ansible#1332]
Is SCRAM SHA 512 is supported along with SSL enabled?

how can I create scram users via the role ?

when I give sasl.mechanism = scram Sha 512
Still my server.properties doesn’t change at all 

seems bothe the configs are same before and after adding sasl.mechanism 

this means do I need to manually override properties of server.properties? Or is there any other way of passing variables inorder to get the correct server.properties?

If so , what is the way ?

**Comment by utkarsh5474** [comment]
Pls refer https://docs.confluent.io/ansible/current/ansible-authenticate.html#configure-sasl-scram-sha-512-authentication

**Comment by suddy417** [comment]
Thank you
