### ISSUE TITLE
Issue with SSL certificate Full Chain Validation

### ISSUE THREAD

**Issue by rnarsupalli-transporeon** [confluentinc/cp-ansible#1334]
Hello Team,

I have generated my custom certificates, which generates the ca.crt, signed cert, key file , fullchain cert.
I have overriden the below variables with respective paths
    ssl_ca_cert_filepath:  # Can be a bundle of ca certs to be included in truststore
    ssl_signed_cert_filepath:# Can be a full chain of certs
    ssl_key_filepath: #keyfile 

But I face the below error under this task:

TASK [confluent.platform.ssl : Verify Cert Chain] *********

MSG:

Cannot complete chain. Stuck at certificate <Certificate(subject=<Name**************************))>

I want to know , why is it not validating the certificate even I give the complete valid cert? Is there anything , I am missing or I need to take care of ,

Here is the error in -vvv mode

{"failed": true, "msg": "Cannot complete chain. Stuck at certificate <Certificate(subject=<Name(C=>, ...)>", "invocation": {"module_args": {"input_chain": "-----BEGIN CERTIFICATE-----*****-----END CERTIFICATE-----\\n\\n-----BEGIN CERTIFICATE-----\\****\n-----END CERTIFICATE-----\\n\\n-----BEGIN CERTIFICATE-----\\nn-----END CERTIFICATE-----\\n", 
"root_certificates": ["path to ca.crt"], "intermediate_certificates": []}}}\r\n', b'Shared connection to server closed.\r\n')
<hostname> Failed to connect to the host via ssh: Shared connection to server closed.
<hostname> ESTABLISH SSH CONNECTION FOR USER: None

**Comment by utkarsh5474** [comment]
Pls share the cp-ansible version.

**Comment by rnarsupalli-transporeon** [comment]
7.3.2-post

**Comment by rnarsupalli-transporeon** [comment]
This was resolved when, all the .crts and .keys are changed to .pem format.
Thanks
