### ISSUE TITLE
Failed to start license store with topic _confluent-command

### ISSUE THREAD

**Issue by suddy417** [confluentinc/cp-ansible#1335]
Hello ,

Failed to start license store with topic _confluent-command . I face this issue when starting up of the Kafka brokers , what should I do to overcome this issue

**Comment by utkarsh5474** [comment]
Hi @suddy417 
We'll be able to help only if we have the complete picture. 
For that, we need cp-ansible branch, your inventory file, and exact verbose error message from the logs.

**Comment by suddy417** [comment]
The cp-ansible branch is 7.3.2-post


Here is the full error 


sudo systemctl status confluent-server.service
● confluent-server.service - Apache Kafka - broker
     Loaded: loaded (/lib/systemd/system/confluent-server.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/confluent-server.service.d
             └─override.conf
     Active: failed (Result: exit-code) sinc
       Docs: http://docs.confluent.io/
    Process: 799 ExecStart=/usr/bin/kafka-server-start /etc/kafka/server.properties (code=exited, status=1/FAILURE)
   Main PID: 799 (code=exited, status=1/FAILURE)
        CPU: 21.127s

 kafka-broker kafka-server-start[799]: org.apache.kafka.common.KafkaException: Failed to start license store with topic _confluent-command. A valid licens> kafka-broker kafka-server-start[799]:         at io.confluent.license.validator.ConfluentLicenseValidator.start(ConfluentLicenseValidator.java:144)
 kafka-broker kafka-server-start[799]:         at kafka.server.KafkaServer.startup(KafkaServer.scala:844)
 kafka-broker kafka-server-start[799]:         at kafka.Kafka$.main(Kafka.scala:108)
 kafka-broker kafka-server-start[799]:         at kafka.Kafka.main(Kafka.scala)
 kafka-broker kafka-server-start[799]: Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 60000ms
 kafka-broker kafka-server-start[799]:  INFO [KafkaServer id=2] shutting down (kafka.server.KafkaServer)
 kafka-broker systemd[1]: confluent-server.service: Main process exited, code=exited, status=1/FAILURE
kafka-broker systemd[1]: confluent-server.service: Failed with result 'exit-code'.
kafka-broker systemd[1]: confluent-server.service: Consumed 21.127s CPU time.

**Comment by suddy417** [comment]
How can I use it as open-source ? Do I need to set any properties in the cp-ansible role ?

**Comment by utkarsh5474** [comment]
Without seeing the inventory file, all I can say is that this is not a cp-ansible issue but an issue from the kafka side itself. 

> How can I use it as open-source ? Do I need to set any properties in the cp-ansible role ?
You can set `confluent_server_enabled: false` to use https://github.com/confluentinc/kafka

**Comment by suddy417** [comment]
Thanks, this resolved my issue
