### ISSUE TITLE
Ldap configuration for Kafka 

### ISSUE THREAD

**Issue by suddy417** [confluentinc/cp-ansible#1338]
How to add ldap configurations using cp-ansible role ?

**Comment by utkarsh5474** [comment]
Can be added using a variable - https://docs.confluent.io/ansible/current/ansible-authorize.html#optional-settings-for-rbac
We don't have a role for configuring an ldap server. That's owned by user.
Our docs are quite helpful. I'd highly suggest going through the docs properly before opening an issue.
