### ISSUE TITLE
When using custom log.dirs for KRAFT cluster, the following task fails

### ISSUE THREAD

**Issue by wushilin** [confluentinc/cp-ansible#1406]
Ansible playbook: 7.4
CP: 7.4

When using custom log.dirs for kafka_controller, the following task fails:

- name: Extract ClusterId from meta.properties on KRaft Controller
  slurp:
    src: "{{ kafka_controller_final_properties['log.dirs'] }}/meta.properties"
  delegate_to: "{{ groups.kafka_controller[0] }}"
  register: uuid_broker

The error is:
fatal: [gssapi-kafka-2.jungle -> gssapi-controller-1.jungle]: FAILED! => {"changed": false, "msg": "file not found: /var/lib/controller/data/meta.properties"}

The file exists within the log.dirs path.

[root@gssapi-controller-1 controller]# cat /opt/cp/data/controller/meta.properties 
#
#Sat May 06 19:19:10 UTC 2023
node.id=10001
version=1
cluster.id=gioVVi8yQFOavO_0w7j6dQ

Not sure if there is something wrong with kafka_controller_final_properties

**Comment by rrbadiani** [comment]
Seems like the logs.dir is is picking up its default value and not getting overridden. It maybe some issue with the defining the logs.dir inside the inventory file but not sure. Can you share the inventory file so I can take a look into it.

**Comment by mansisinha** [comment]
This is a limitation in our code. Please define
kafka_controller_custom_properties:
      log.dirs:
in gloval vars instead of inside kafka_controller since broker also needs to use this variable.
