### ISSUE TITLE
Implement encryption at rest

### ISSUE THREAD

**Issue by datumgeek** [confluentinc/cp-ansible#141]
This project is AWESOME...  The Kerberos and SSL support is fantastic...

It would really complete the picture if LUKS or KMS disk encryption were implemented so that only the kafka user could decrypt the kafka segment files...

**Comment by JumaX** [comment]
@datumgeek Really interesting idea.  I think this has bigger implications for the platform as a whole however, so I have brought it up with our Product Management team to discuss it further.

**Comment by JumaX** [comment]
@datumgeek Since this is not a CP-Ansible specific issue/question, I am going to go ahead and close this out.  Thanks again for the suggestion.
