### ISSUE TITLE
kafka_connectors is not supporting RBAC clusters?

### ISSUE THREAD

**Issue by ElfoLiNk** [confluentinc/cp-ansible#1413]
**Describe the issue**
Not able to register a connector config in Kafka Connect because the POST connectors API requires authentication.

**To Reproduce**
Configure kafka connectors with rbac enabled

**Expected behaviour**
Be able to deploy kafka connectors in an rbac cluster

**Logs**
TASK [confluent.platform.kafka_connect : Register connector configs and remove deleted connectors for Multiple Clusters] ***
Wednesday 31 May 2023  14:39:52 +0200 (0:00:00.190)       0:07:55.438 *********
failed: [[xxxxx](http://xxxxx/) -> [xxxxx](xxxxx)] (item=kafka_connect_serial) => {"ansible_loop_var": "item", "changed": false, "item": "kafka_connect_serial", "message": "HTTP Error 401: Unauthorized", "msg": "An error occurred while running the module"}

**Environment (please complete the following information):**
 - OS: RHEL 8
 - CP-Ansible Branch: 7.2.5
 - Ansible Version: 2.11

**Comment by rrbadiani** [comment]
Closing this  because it has been done in https://github.com/confluentinc/cp-ansible/pull/1537
