### ISSUE TITLE
rhel/centos 8 support

### ISSUE THREAD

**Issue by t2y** [confluentinc/cp-ansible#150]
centos 8 was released at 2019-09-24.

* https://wiki.centos.org/Manuals/ReleaseNotes/CentOS8.1905?action=show&redirect=Manuals%2FReleaseNotes%2FCentOSLinux8

The confluent platform hasn't support rhel/centos 8 yet. I couldn't find a plan to support.

* https://docs.confluent.io/current/installation/system-requirements.html#operating-systems

Do you have a plan to support rhel/centos 8? It's helpful for me to consider upgrading schedule.

**Comment by JumaX** [comment]
@t2y I would recommend opening a Support Ticket with our Support team to discuss this further, as this is a platform Specific question, and not just related to CP-Ansible.  You can reach our support organization at support.confluent.io.
