### ISSUE TITLE
Tasks that use CLI that use Kraft cluster.id (ie. kafka-storage) fail when cluster.id that start with hyphen

### ISSUE THREAD

**Issue by DennisFederico** [confluentinc/cp-ansible#1587]
I started with a ZK cluster with id "-v5on6u0TVW2BvW4hazZTw" ... after upgrading to Kraft using the migration playbook, I cannot run the playbook again to change broker properties, as the task "Format Storage Directory" uses the kafka-storage CLI without quoting the cluster.id

See attached images including running the command manually, as the Ansible error output was not clear enough

<img width="1552" alt="Screenshot 2024-04-30 at 14 12 31" src="https://github.com/confluentinc/cp-ansible/assets/1193234/192f8d9b-a489-43f3-af76-f79bd57f30e8">

<img width="1043" alt="Screenshot 2024-04-30 at 14 14 12" src="https://github.com/confluentinc/cp-ansible/assets/1193234/cf13e4d9-9ad7-4f66-ab97-9b45e3d0bae7">

<img width="653" alt="Screenshot 2024-04-30 at 13 59 29" src="https://github.com/confluentinc/cp-ansible/assets/1193234/edf14aac-affe-456d-9501-7a803a786ec8">

<img width="986" alt="Screenshot 2024-04-30 at 13 57 52" src="https://github.com/confluentinc/cp-ansible/assets/1193234/2c950db2-05ec-414d-91a3-378bd546a502">

But it seems that quoting the argument doesn't work either

**Comment by mansisinha** [comment]
thanks @DennisFederico  for pointing this out, I will fix this bug

**Comment by mansisinha** [comment]
closing since the fix has been merged
