### ISSUE TITLE
The roles are quite not really usable like this

### ISSUE THREAD

**Issue by vfoucault** [confluentinc/cp-ansible#16]
It would require a lot of effort for using these roles.
It would be better to have a single role with some subroles.

eg: cp-ansible/tasks/zookeeper/main.yml
                                  kafka-broker/main.yml

Along with something like `confluent_role: ["zookeeper", "kafka-broker"]` that will include the correct tasks

**Comment by cotedm** [comment]
We choose to use the ansible built-in role functionality versus creating subroles at this time.
