### ISSUE TITLE
Chaning Restart=no to Restart=always

### ISSUE THREAD

**Issue by lavalex** [confluentinc/cp-ansible#1608]
**Environment (please complete the following information):**
 - CP-Ansible Branch: 7.6.0-post

Hello,

Actually two questions:

1. Why in all components, beside Control Center, services in systemd are created with Restart=no?
2. What will be the most efficient way to modify via Ansible this setting? Copying override.conf?

Thank you in advance.

**Comment by MosheBlumbergX** [comment]
Hi @lavalex ,

cp-ansible doesn't actually set this value at all, it's the default of Confluent systemd files, I can't speak to why it's not being set though. 


To override: 

```
    schema_registry_service_overrides:
      Restart: always
```

**Comment by lavalex** [comment]
Thanks!
