### ISSUE TITLE
I can't git clone 

### ISSUE THREAD

**Issue by khayashi4337** [confluentinc/cp-ansible#167]
I can't git clone

windows10

```
Cloning into 'cp-ansible'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
error: filename in tree entry contains backslash: '\'.00 KiB/s
fatal: Not all child objects of 92f078938637f5e0f2588b4ba96be1de9b817105 are 
reachable
fatal: index-pack failed
```

**Comment by khayashi4337** [comment]
There was no problem with centos.

**Comment by JumaX** [comment]
@khayashi4337 Generally this error is generated because there are characters in filenames that the Windows file system cannot handle.  This also explains why it works on CentOS.  Windows is not a supported platform for Apache Kafka or Confluent Platform at this time.
