### ISSUE TITLE
Molecule tests

### ISSUE THREAD

**Issue by cricket007** [confluentinc/cp-ansible#171]
I assume this repo is tested manually (via Jenkins perhaps)? 

What about adding molecule tests? - https://github.com/ansible/molecule

**Comment by JumaX** [comment]
@cricket007 Thanks for the info about molecule.  We currently do automated testing on this repo.  We will definitely give molecule a review and see if it makes sense for us.

**Comment by cricket007** [comment]
FYI, I noticed there were some forks that already include it 

e.g. https://github.com/ContentSquare/cp-ansible/tree/master/molecule

**Comment by cricket007** [comment]
Link #230

**Comment by JumaX** [comment]
@cricket007 Just a quick update to let you know that we are actively working on integrating molecule testing.  We are hoping to have something ready soon.  Thanks again for the heads up on this, it's a very powerful feature/function.

**Comment by JumaX** [comment]
@cricket007 We now have molecule testing in the 5.5.0 release.  We have a role called confluent.test that contains the different scenarios.  We are still working on documentation for it, but thanks for letting us know about this, as its a massive improvement for both testing and local development.

**Comment by cricket007** [comment]
Glad to hear it 👍🏼
