### ISSUE TITLE
Error while installing Confluent using ansible

### ISSUE THREAD

**Issue by din-heg** [confluentinc/cp-ansible#172]
I am trying to install confluent using ansible as outlined in this document:
https://docs.confluent.io/current/installation/installing_cp/cp-ansible.html
I have not enabled any kerberos setting in hosts.yml but I still get kerberos related errors.

The attached file contains the errors.
[
[failure.txt](https://github.com/confluentinc/cp-ansible/files/4084988/failure.txt)
](url)

**Comment by JumaX** [comment]
Hello @din-heg Thanks for your question.  An initial review of your error shows that you are running an un-supported version of the Ansible runtime, specifically 2.5.1.  As per our documentation, you need to be running Ansible 2.7.x or later.  https://docs.confluent.io/current/installation/installing_cp/cp-ansible.html#general-requirements

I suspect the older version you are running maybe having issues interpreting variable names.  I would recommend you upgrade your version of Ansible and try again.

**Comment by din-heg** [comment]
I did upgrade the Ansible and was able to install successfully.  Thanks for your help.
