### ISSUE TITLE
Add proxy variable for the yum repositories

### ISSUE THREAD

**Issue by julienlefur** [confluentinc/cp-ansible#198]
When the confluent RPMs are mirrored in a local repository, the parameter "proxy: _none_" for YUM repos must be added. It would be great to add variables like:
```
 confluent_common_repository_redhat_main_proxy: _none_
 confluent_common_repository_redhat_dist_proxy: _none_
```

here: 
https://github.com/confluentinc/cp-ansible/blob/fe427a4f1ff1191dff75e37200855064ccb2f721/roles/confluent.common/defaults/main.yml#L4-L12

And in the task file:
`proxy: "{{confluent_common_repository_redhat_main_proxy | default(omit) }}"`
and
`proxy: "{{confluent_common_repository_redhat_dist_proxy | default(omit) }}"`

here
https://github.com/confluentinc/cp-ansible/blob/fe427a4f1ff1191dff75e37200855064ccb2f721/roles/confluent.common/tasks/redhat.yml#L2-L12

**Comment by domenicbove** [comment]
Take a look at this PR please: https://github.com/confluentinc/cp-ansible/pull/202

**Comment by JumaX** [comment]
@julienlefur This change has been merged into PR #202, will close this out.

**Comment by julienlefur** [comment]
@JumaX Thank you.
For the yum module i think that the no_proxy env variable is not used. The only way to bypass the proxy is to set proxy=_none_
So my issue is still open for me. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by julienlefur** [comment]
@JumaX Never mind. I can use the variable `custom_yum_repofile`.
