### ISSUE TITLE
pass keystore path

### ISSUE THREAD

**Issue by smedegaard** [confluentinc/cp-ansible#210]
in the custom_certs.yml should we not pass the `keystore_path` for the `-keystore` path?

https://github.com/confluentinc/cp-ansible/blob/336b6f4a2d4297a06860aa06832b82259fc33f29/roles/confluent.ssl/tasks/custom_certs.yml#L27

**Comment by JumaX** [comment]
Hello @smedegaard thanks for the question.  In this instance, {{truststore_path}} should not be {{keystore_path}} as the -keystore switch is actually a generic switch for specifying the name of a keystore, in a generic sense.  As in, the place where you store keys, not keystore vs truststore.  There is no -truststore switch for example. Being that this code is creating the truststore, {{truststore_path}} is the correct variable.

**Comment by smedegaard** [comment]
@JumaX , thanks for the clarification! I realized this after further reading. 👍
