### ISSUE TITLE
Zookeeper dataDir vs dataLogDir

### ISSUE THREAD

**Issue by danielyahn** [confluentinc/cp-ansible#214]
It seems like cp-ansible doesn't have distinction between dataDir (snapshot) and dataLogDir (transaction log). `dataLogDir` needs to be exposed as an option.

Per https://zookeeper.apache.org/doc/r3.1.2/zookeeperAdmin.html It is the best practice to separate them.
> This option will direct the machine to write the transaction log to the dataLogDir rather than the dataDir. This allows a dedicated log device to be used, and helps avoid competition between logging and snaphots.

**Comment by JumaX** [comment]
@danielyahn Thanks for the feedback.  We will look into adding this capability in a future release.  That being said, generally most customers have a dedicated disk for Zookeeper, so this very seldom comes up.  Where I have seen it be an issue, is when a customer colocates multiple components on the same host with Zookeeper, that are quite IO intensive and thus Zookeeper gets starved for bandwidth.

**Comment by cricket007** [comment]
Regarding dedicated mounting points, I suppose the [mount module](https://docs.ansible.com/ansible/latest/modules/mount_module.html) is too granular for managing?

Those tasks should likely be done before these playbooks?

**Comment by danielyahn** [comment]
@JumaX I think the more strict spec I've seen actually allocates two separate disks (even when Zookeeper has a dedicated node). 

From enterprise reference architecture
![image](https://user-images.githubusercontent.com/19540773/77075726-c94b1600-69c0-11ea-8ce1-f2ed0d2af9dc.png)

@cricket007 
It looks like `dataDir` has some automation around ownership (https://github.com/confluentinc/cp-ansible/blob/5.4.1-post/roles/confluent.zookeeper/tasks/main.yml#L40). I think it would be ideal to have parametrization on `dataLogDir` and similar orchestration steps as `dataDir`

**Comment by JumaX** [comment]
@OneCricketeer Correct.  We will not handle mount points/OS configuration, this up to the admin.

@danielyahn Yes, I've seen this recommended before, however I've almost never actually seen it in use/needed in practice.  This includes for extremely large clusters with thousands of nodes.  I believe this recommendation harkens back to days when disks and disk controllers were much slower.  I think it maybe a bit out of date by today's standards.  I still think we should go ahead and make this a configuration option however.

**Comment by Fobhep** [comment]
+1 on making this a configuration option

**Comment by OneCricketeer** [comment]
Please show your support by using the upvote feature rather than send notifications to us all via comment (or submit the PR). Thanks!

@Fobhep

**Comment by JumaX** [comment]
Just a quick update to say you can set custom properties for all components in the 6.0 release.  So you can set this pretty easily in the future.

**Comment by JumaX** [comment]
@danielyahn  We merged a change to break out the logs a few days ago.  You can see PR 424.  It's not required in most modern systems as disk IO is generally not a bottleneck with the move away from spinning disks, however you can now easily implement if desired.  Thanks again for the request/report.
