### ISSUE TITLE
Zookeeper SASL authentication

### ISSUE THREAD

**Issue by danielyahn** [confluentinc/cp-ansible#215]
There are some instruction on how to secure zookeeper manually:
- https://docs.confluent.io/current/security/zk-security.html#zk-security
- https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_scram.html#zk which suggests to use SASL/DIGEST-MD5

Can we add orchestration for these?

**Comment by JumaX** [comment]
@danielyahn Thanks for the feedback.  We will look at addressing this in a future release.

**Comment by AntonSmolkov** [comment]
@danielyahn Hi.
I also have got concerns about unprotected zookeeper installations.
Take a look on my fork, you may find it helpful.

**Comment by JumaX** [comment]
@AntonSmolkov Thanks for the feedback.  We plan on addressing this soon.  We had a PR for this, however we found a bug with ZK itself that needed to be corrected before it could be merged.

**Comment by AntonSmolkov** [comment]
@JumaX  Hmm. What kind of bug? Need to know, cause i'm gonna use it in production soon.

**Comment by JumaX** [comment]
@AntonSmolkov I don't have the details in front of me, but as I recall, it was specific to upgrading zookeeper.  My suggestion would be to stand up antest env and test upgrades thoroughly, make sure you have data in zookeeper before the upgrade can validate it after the upgrade.

**Comment by AntonSmolkov** [comment]
Ok, got it, thanks!

**Comment by domenicbove** [comment]
Digest md5 has been added with these prs: 
https://github.com/confluentinc/cp-ansible/pull/285
https://github.com/confluentinc/cp-ansible/pull/286
