### ISSUE TITLE
Add passphrase configuration for custom-cert keys 

### ISSUE THREAD

**Issue by julienlefur** [confluentinc/cp-ansible#221]
Would it be possible to add the parameter `-passin` to configure a passphrase for the key.pem file for custom certs:

https://github.com/confluentinc/cp-ansible/blob/d54f68b504093c94f7feadc8c409fa2ce842e9ec/roles/confluent.ssl/tasks/custom_certs.yml#L34-L41

**Comment by domenicbove** [comment]
Just created this PR: https://github.com/confluentinc/cp-ansible/pull/222 
Please review

**Comment by julienlefur** [comment]
@domenicbove Thanks. Exactly what I needed.
