### ISSUE TITLE
[question] Use-cases of _default_ variables

### ISSUE THREAD

**Issue by cricket007** [confluentinc/cp-ansible#224]
Example `zookeeper_default_user`

This seems like an Ansible anti-pattern if that default is defined only to be checked in an if-else to be discarded later

Why not just `zookeeper_user: <default>` and let the user define it themselves in their variables?

Reference: https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-default-variables

**Comment by JumaX** [comment]
@cricket007 Thanks for the question.  My thoughts are, that this is actually easier for the end user in this form, as we give them a default that they don't have to think about or set, but can override if they wish.  We've had requests from users to be able to set their own users, while we've had others be happy with the defaults.  So to me, this seems like the simplest approach to satisfy both groups.  

Perhaps @domenicbove has further thoughts on this?

**Comment by cricket007** [comment]
> we give them a default that they don't have to think about or set, but can override if they wish

Right, and having simply `zookeeper_user` (in *either* defaults/main.yml or the higher priority variables such as the inventory or cli args) allows for that use case perfectly fine. 

My point is that this logic could be simplified 

`{{ zookeeper_user if zookeeper_user != zookeeper_default_user else '' }}`

To simply 

`{{ zookeeper_user | default() }}`

Because the default default value parameter is an empty string

Source: https://github.com/pallets/jinja/blob/8a49e066af3d88d1edb34aa1680b668c959dfcf7/jinja2/filters.py#L267

**Comment by domenicbove** [comment]
Hey happy to get advice on this one, there are two variables that need to be set:

```
zookeeper_user: confluent-kafka
zookeeper_service_overrides:
  LimitNOFILE: 100000
  User: <ideally set to empty string if zookeeper_user remains confluent-kafka>
```

The logic is this- customer can update `zookeeper_user`, but only if they do, do i want to update `zookeeper_service_overrides.User`. The templating for the service override files only writes to the file if the value is a non empty string.

Can we use the default filter to achieve this ^^?

**Comment by cricket007** [comment]
Hey @domenicbove 

Related question: What's the benefit of setting an empty string for the user or group in the service? 

What permissions/security would that offer?

**Comment by domenicbove** [comment]
so if you look at the confluent.zookeeper/templates/override.conf.j2 youll see that it loops over the zookeeper_service_overrides dictionary and only writes to the file the key/values if the value is a non empty string. 

Now the use of this overrides.conf file is to override what is in the service unit file for each service. for zookeeper this is `/usr/lib/systemd/system/confluent-zookeeper.service` and if you were to examine that file there is a line in it:
`User=confluent-kafka`

Furthermore I do not what to write `User=confluent-kafka` into `/etc/systemd/system/confluent-zookeeper.service.d/override.conf` I only want to write customized users into that file

**Comment by JumaX** [comment]
@cricket007 @domenicbove I think the current approach makes sense relative to what we are trying to achieve, and respecting that are not modifying anything unless we have to (override.conf).  Unless there are further suggestions/questions, going to close this out.

**Comment by cricket007** [comment]
I still think there is a way to do it with only one variable and letting the user override that, but when I get time, I'll see if I can work that out. 

Thanks for the responses anyway 😄
