### ISSUE TITLE
Allow to set repo base url variable for repositories

### ISSUE THREAD

**Issue by jeqo** [confluentinc/cp-ansible#225]
Similar to https://github.com/confluentinc/cp-ansible/issues/198

Custom repository file could get stale when upgrading, as it has the version available, e.g.:

```
[Confluent]
baseurl = https://artifactory.company.com/artifactory/confluent-rpm-remote/5.3
enabled = 1
gpgcheck = 1
gpgkey = https://artifactory.company.no/artifactory/confluent-rpm-remote/5.3/archive.key
```

To avoid having to align this file with current version manually I'd like to suggest the following options:

1. Add a base_url variable for repositories:

```
confluent_repo_baseurl: "https://packages.confluent.io/rpm"
confluent_common_repository_redhat_main_baseurl: "{{confluent_repo_baseurl}}/{{confluent_repo_version}}"
confluent_common_repository_redhat_main_gpgcheck: 1
confluent_common_repository_redhat_main_gpgkey: "{{confluent_repo_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_main_enabled: 1

confluent_common_repository_redhat_dist_baseurl: "{{confluent_repo_baseurl}}/{{confluent_repo_version}}/7"
confluent_common_repository_redhat_dist_gpgcheck: 1
confluent_common_repository_redhat_dist_gpgkey: "{{confluent_repo_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_dist_enabled: 
```

2. Change `copy` to `template`:

```
- name: Add Custom Repo file
  template:
    src: "{{custom_yum_repofile_filepath}}"
    dest: /etc/yum.repos.d/custom-confluent.repo
  when: custom_yum_repofile|bool
```

```
[Confluent]
baseurl = https://artifactory.company.com/artifactory/confluent-rpm-remote/{{confluent_repo_version}}
enabled = 1
gpgcheck = 1
gpgkey = https://artifactory.company.no/artifactory/confluent-rpm-remote/{{confluent_repo_version}}/archive.key
```

**Comment by domenicbove** [comment]
Is number 1 related to the problem statement? I would say that is a code improvement though. 

And number 2 implies that cp-ansible users understand templating. Wouldn't it be possible for a customer to just update their custom repofile prior to the upgrade? (this step probably needs to be documented!)

**Comment by jeqo** [comment]
> Is number 1 related to the problem statement? I would say that is a code improvement though.

If `1` would be available--at least in my case--, I wouldn't need to recur to a custom file. 

> And number 2 implies that cp-ansible users understand templating. 

Not necessarily. If users keep using a file without jinja2 annotation, the same file will be _copied_ to the dest. On the other hand, I'd assume Ansible users will have an understanding of templating to start with.

> Wouldn't it be possible for a customer to just update their custom repofile prior to the upgrade? 

That's one thing I'm trying to avoid with these alternatives. Asking users to update repofiles would be failure-prone.

**Comment by domenicbove** [comment]
I just added this: which has number 1 in it: https://github.com/confluentinc/cp-ansible/pull/226
Variables slightly different than requested but should work for you!

**Comment by jeqo** [comment]
Thanks @domenicbove! 

Do you think alternative 2 would be useful to keep this issue open?

**Comment by domenicbove** [comment]
@jeqo Ah good point about templating- i didn't realize that it would act like a copy if the template has no jinja in it (but it makes sense!)... I can't speak to how useful that change would be for people. I would say close it
