### ISSUE TITLE
Support JMX Exporter when upgrading

### ISSUE THREAD

**Issue by jeqo** [confluentinc/cp-ansible#231]
Currently upgrading tasks only support Jolokia endpoints to check controller and URP metrics: 

https://github.com/confluentinc/cp-ansible/blob/e00a0850a00b4352b07b4a3de9ed9033ea84f0d5/tasks/create_ordered_kafka_groups.yml#L9

Prometheus JMX exporter endpoint should be also supported as is part of the installation.

**Comment by JumaX** [comment]
Hello @jeqo Thanks for the request.  We will look into this for a future release.

**Comment by domenicbove** [comment]
@jeqo in 610, the upgrades work without jmx exporter and jolokia, I think this can be closed. LMK if you have objections

**Comment by jeqo** [comment]
@domenicbove agree, with 6.1.0 this should be solved. Thanks! Closing this.
