### ISSUE TITLE
Add Vagrant configuration

### ISSUE THREAD

**Issue by jeqo** [confluentinc/cp-ansible#234]
A Vagrant configuration(s) would help to test Ansible roles and have an easy way to showcase features, similar to Kafka one: https://github.com/apache/kafka/blob/trunk/Vagrantfile

**Comment by domenicbove** [comment]
Molecule is in the process of being added with Docker drivers: https://github.com/confluentinc/cp-ansible/pull/232

This is probably the best guide i've found on it: https://www.toptechskills.com/ansible-tutorials-courses/rapidly-build-test-ansible-roles-molecule-docker/

This enables you to run `molecule converge` and have the entire platform up running on docker containers.

Down the line, we can add the vagrant driver as well (or ec2 even). But I think for the use case of showcasing features/ dev/testing docker works great

**Comment by jeqo** [comment]
Looking forward to check this molecule thingy :) I'll close this one and create a new one if the need for vagrant inside molecule appears. Thanks!
