### ISSUE TITLE
Yamllint and ansible-lint

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#237]
First of all - thanks for creating those playbooks and roles. They are very helpful!
I am using ansible for a lot of my customers and I follow a rather strict linting policy and have some "errors" from this repository in that terms.
I was wondering if the maintainers of this repository would care about some "improvements" in terms of yamllint and ansible-lint?

**Comment by domenicbove** [comment]
@Fobhep Yes, linting has been on my mind, but very far back in the backlog :) 
Would you be able to contribute what you have?

Also the molecule tests that I am working to add has a step for lint checks, so we will want to make sure it all works together.

**Comment by Fobhep** [comment]
sure - I can cobble together an initial PR in the next couple days :)

**Comment by Fobhep** [comment]
- [ ] Add yaml-linting #240 
- [ ] Add ansible-linting
