### ISSUE TITLE
the meaning of keystore_keypass

### ISSUE THREAD

**Issue by smedegaard** [confluentinc/cp-ansible#239]
**The Question**
What is the point of the `keystore_keypass` variable?

**The Context**
I'm trying to use the playbook with custom certs, but having a hard time making it work.
I have no previous experience with Java's trust- and keystores so assume ignorance on my part.

using the `custom_certs` play, I do get the trust- and keystores. But the `confluent-server` service fails with:

```
java.security.UnrecoverableKeyException: 
Get Key failed:
Given final block not properly padded. 
Such issues can arise if a bad key is used during decryption.
```

THE INTERNET tells me that this can be caused by several things, but likely is a bad password.
So on a whim I set `listener.name.external.ssl.key.password` to the same value as `listener.name.external.ssl.keystore.password` and the service now starts.

I then had a look at [`roles/confluent.kafka_broker/templates/listener.j2`](https://github.com/confluentinc/cp-ansible/blob/f53d3250721f9364fb2081a45a183161df0e1d59/roles/confluent.kafka_broker/templates/listener.j2#L6) where I see that `kafka_broker_keystore_keypass` is used.

Going back to `roles/confluent.ssl/tasks/custom_certs.yml`, `keystore_keypass` is nowhere to be found. 

the use of a hard-coded key password is adding to my confusion.
`-passout pass:mykeypassword`

Please excuse my ignorance, but I'm thoroughly confused.

**Comment by JumaX** [comment]
Hello @smedegaard thanks for your question.

When you generate keys and certificates there are generally three passwords you can set, one on each storage container (Keystore, Truststore) and a third on the private key.  Private key passwords on generally mandatory to set. 

If you look at our self signed tasks:

https://github.com/confluentinc/cp-ansible/blob/5.4.1-post/roles/confluent.ssl/tasks/self_signed_certs.yml

You can see that even when we do the initial import of the CA cert into the truststore, we set a password on the key with the `-keypass` switch:

`- name: Create Truststore and Import the CA Cert
  shell: |
    keytool -noprompt -keystore {{truststore_path}} \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file /var/ssl/private/generation/{{ssl_self_signed_ca_cert_filename}} \
      -storepass {{truststore_storepass}} \
      -keypass {{truststore_storepass}} {{extra_args}}`

So to confirm, there is a password set on the Containers which contain your certificates, and there is password on the private key.

Hope that helps explain.

**Comment by smedegaard** [comment]
Thanks for the answer @JumaX !

I really appreciate you taking the time to explain this. 

Sadly, I must admit that I'm still confused.

The flag you refer to `-keypass {{truststore_storepass}}` uses `truststore_storepass`, not `keystore_keypass`.

When searching for `keystore_keypass` in this repo here on Github [I find it 6 times](https://github.com/confluentinc/cp-ansible/search?q=keystore_keypass&unscoped_q=keystore_keypass). One for each of the roles that use the SSL role. This makes sense. 

But the search does not reveal a single place where the `keystore_keypass` is used in a play.
Not In the tasks in the SSL role. Nowhere. So either there's some Ansible trickery that I'm missing (likely 😀) or this variable is redundant since only the component specific keystore_keypass are used.

For example:
[confluent.kafka_broker/templates/server.properties.j2](https://github.com/confluentinc/cp-ansible/blob/f53d3250721f9364fb2081a45a183161df0e1d59/roles/confluent.kafka_broker/templates/server.properties.j2#L53) refers to the specific `kafka_broker_keystore_keypass`.

Assuming I'm correct, this will make the property files incorrect since it's getting `<some_component>.ssl.key.password={{<some_component>_keystore_keypass}}`. Where `<some_component>_keystore_keypass` is not used in any of the SSL tasks.

Again, I really do appreciate you (or anyone) taking time to answer this. And if I'm wrong about this please see this as an opportunity to share your knowledge. 😅

Regards, 
Anders

**Comment by domenicbove** [comment]
My understanding is that for a java keystore you can have a password on the keystore itself, and on a key within it. Those passwords may be the same thing, which you've pointed out in the code.

Can you provide a copy of you inventory file? Also the scripts that generated the certificates/keys is helpful

**Comment by smedegaard** [comment]
Hi @domenicbove , 

I can't share the repo, but here's the gist of it.

I'm using a slightly modified version of the [`custom_certs`](https://gist.github.com/smedegaard/a7b8c85312a5ba6065ad0ec6187e05e7). The CA, CA key and signed cert is copied to each vm by a company Ansible job. So I've removed the plays to copy those, and specified their paths in the respective variables.

Defined variables in the inventory are
```
 kafka_broker_default_listeners:
      external:
        name: EXTERNAL
        port: 9093
        ssl_enabled: true
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
    kafka_broker_custom_listeners:
      internal:
        name: INTERNAL
        port: 9092
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
```

and in `group_vars/all.yml`

```
self_signed: false
ssl_custom_certs: true
regenerate_ca: true

ssl_ca_cert_filepath: "my_ca.crt"
ssl_signed_cert_filepath: "my_signed_cert.cer"
ssl_key_filepath: "my_key"
```

In desperation I've set all `<component>_keystore_keypass` to `<component>_keystore_storepass` in `confluent.variables_handler/defaults/main.yml`

for example:
`kafka_broker_keystore_keypass: "{{ vault.kafka_broker_keystore_storepass }}"`


The `confluent-server` service works with this config. 
`schema-registry` is failing to start, but that's another topic (maybe?.)

**Comment by domenicbove** [comment]
I think you are missing the ssl_key_password var. Which would be the key password for `ssl_key_filepath`
https://github.com/confluentinc/cp-ansible/blob/5.4.1-post/roles/confluent.ssl/tasks/custom_certs.yml#L39

What branch of cp-ansible are you using?

**Comment by domenicbove** [comment]
Oh ya I just saw your link, it appears you don't pass a key password here:
https://gist.github.com/smedegaard/a7b8c85312a5ba6065ad0ec6187e05e7#file-custom_certs-yml-L19

And I think whats happening is the subsequent code updates the keypass within the keystore created. So maybe thats the fix, you need a keypass var

**Comment by smedegaard** [comment]
I branched out from `5.4.0-post`, but I've merged `5.4.1-post`. 

There's no password for the ssl key (I know, but it's not my decision).
That's why I don't have ` -passin pass:{{ssl_key_password}}`.

And the `keystore_keypass` is not the same as `ssl_key_password`. One of my initial reasons for confusion 😄

**Comment by domenicbove** [comment]
yep this change was recent- someone pointed it out to me that there wasnt a password on the key
https://github.com/confluentinc/cp-ansible/issues/221
https://github.com/confluentinc/cp-ansible/pull/222

"merge 18 days ago"

**Comment by smedegaard** [comment]
Yeah, I saw the PR and thought my problems where solved for a happy 10 minutes. 😄 

But  the CA key that's provided by my company has no password. That's what we are providing with  `-passin pass:{{ssl_key_password}}`, right?

So I don't actually need ` -passin pass:{{ssl_key_password}}`.

Please correct me if I'm wrong

**Comment by domenicbove** [comment]
This is pretty hard to do over comments, I am available for a call if you'd like.

It sounds like:

- your custom certs do not have passwords

- the custom certs tasks are successfully creating a keystore with this code (the deststorepass and destkeypass are set to the same thing):
```
- name: Create Keystore
  shell: |
    keytool -importkeystore \
      -srckeystore /var/ssl/private/generation/client.p12 \
      -srcstoretype pkcs12 \
      -srcstorepass {{ keystore_keypass }} \
      -destkeystore {{keystore_path}} \
      -deststoretype pkcs12 \
      -deststorepass {{ keystore_storepass }} \
      -destkeypass {{ keystore_storepass }} {{extra_args}}
```

- But then in server.properties, these vars are not set correctly:

```
listener.name.{{listener.value.name|lower}}.ssl.keystore.location={{kafka_broker_keystore_path}}
listener.name.{{listener.value.name|lower}}.ssl.keystore.password={{kafka_broker_keystore_storepass}}
listener.name.{{listener.value.name|lower}}.ssl.key.password={{kafka_broker_keystore_keypass}}
```

Another important line is here: https://github.com/confluentinc/cp-ansible/blob/5.4.1-post/roles/confluent.variables_handlers/defaults/main.yml#L116
Which essentially says that unless you provide a keystore (not your scenario, make sure ssl_provided_keystore_and_truststore is not set to true) then the keypass var is set to the storepass var

Can you provide the server.properties ansible creates and what it should be? (you can paste in dummy passwords if there are security concerns just make sure the differences are clear)

**Comment by smedegaard** [comment]
@dominicbove Are you available in an hour?

Where can I reach you ? Slack?

**Comment by domenicbove** [comment]
```
    kafka_broker_custom_listeners:
      internal:
        name: INTERNAL
        port: 9091
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
      external:
        name: EXTERNAL
        port: 9092
        ssl_enabled: true
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
```

**Comment by domenicbove** [comment]
make a PR for something like this 
```
- name: Put Key and Signed Cert into pkcs12 Format
  shell: |
    openssl pkcs12 -export \
      -in /var/ssl/private/generation/signed.crt \
      -inkey /var/ssl/private/generation/key.pem \
      -passin pass:{{ssl_key_password}} \
      -out /var/ssl/private/generation/client.p12 \
      -name kafkassl \
      -passout pass:mykeypassword
  when: ssl_key_password is defined

- name: Put Key and Signed Cert into pkcs12 Format
  shell: |
    openssl pkcs12 -export \
      -in /var/ssl/private/generation/signed.crt \
      -inkey /var/ssl/private/generation/key.pem \
      -out /var/ssl/private/generation/client.p12 \
      -name kafkassl \
      -passout pass:mykeypassword
  when: ssl_key_password is not defined
```

**Comment by domenicbove** [comment]
This can be closed because it was all resolved in this pr: https://github.com/confluentinc/cp-ansible/pull/269
