### ISSUE TITLE
ansible-container

### ISSUE THREAD

**Issue by OneCricketeer** [confluentinc/cp-ansible#242]
Now that these Ansible playbooks are production supported, perhaps they should be used to build the Docker images rather than a combo of bash scripts? 

https://docs.ansible.com/ansible-container/

---

Common:
- https://github.com/confluentinc/confluent-docker-utils
- https://github.com/confluentinc/common-docker

Zookeeper, Kafka, Connect
- https://github.com/confluentinc/kafka-images

Kafkacat
- https://github.com/confluentinc/kafkacat-images

ksqlDB
- https://github.com/confluentinc/ksql-images

C3
- https://github.com/confluentinc/control-center-images

REST Proxy
- https://github.com/confluentinc/kafka-rest-images

Schema Registry
- https://github.com/confluentinc/schema-registry-images

**Comment by JumaX** [comment]
@cricket007 thanks for the request.  I will file an internal feature request to have this reviewed/investigated for viability.   Thanks again for this.

**Comment by cricket007** [comment]
Alternative - https://github.com/ansible-community/ansible-bender

**Comment by domenicbove** [comment]
There is an entire Jenkins build process for those docker images. And from what I can tell its is built/well rounded. What is the value of redoing it with ansible?

**Comment by cricket007** [comment]
> There is an entire Jenkins build process for those docker images

Not sure I see why that is an issue. 

> it is built/well rounded

That's good. 

> What is the value of redoing it with ansible?

Probably none. Other than it creates a single place for maintaining how the platform is installed in individual pieces, as I said initially, _rather than bash commands_.

**Comment by cricket007** [comment]
Hmm. This is deprecated - https://github.com/ansible/ansible-container/tree/master

That is mainly why I put the alternative option

**Comment by JumaX** [comment]
@cricket007 Thanks again for the feedback.  Understood about the deprecation.  I've filed an internal JIRA for us to research this a bit in the future to see what makes sense.  It's not a guarantee we will change it, but by logging it, we can allocate some time to figure out what makes sense here.  CC: @domenicbove

**Comment by JumaX** [comment]
@OneCricketeer Since the original tool is deprecated, and this is a bit further down our "to do" list, I am going to go ahead and close out this issue for now.  Thanks again for the suggestions, please keep them coming.
