### ISSUE TITLE
same ksql_streams_state_dir set two diffrent mode

### ISSUE THREAD

**Issue by xiaobao623** [confluentinc/cp-ansible#244]
ksql task conflict
same ksql_streams_state_dir set two diffrent mode, the first is line38 mode=0755, the second is line68 mode=0750
 

- name: Set Ksql streams dir permissions
  file:
    path: "{{ksql.properties['ksql.streams.state.dir']}}"
    owner: "{{ksql_user}}"
    group: "{{ksql_group}}"
    state: directory
    mode: 0755  #line38

- name: Change streams directory ownership
  file:
    path: "{{ksql_streams_state_dir}}"
    owner: "{{ksql_user}}"
    group: "{{ksql_group}}"
    state: directory
    mode: 0750

**Comment by JumaX** [comment]
@xiaobao623 Thanks for the report, will investigate this.  Can you confirm the exact impact it's having on your installation?  Are you seeing any undesired behaviour?  This will help us prioritise.

Thanks again for the feedback!

**Comment by cricket007** [comment]
I'm not sure this would cause an error as the higher-order bits are the same... Does seem redundant, though, and 750 makes sense if you don't want others to be able to read that dir

**Comment by xiaobao623** [comment]
There no impact install, and work fine. Only show changed info every time when I run the playbook.

**Comment by JumaX** [comment]
Hi @xiaobao623  we have now resolved this in the following PR, on the 5.5.0-post branch.  It was redundant so we removed the second file permission setting task.

https://github.com/confluentinc/cp-ansible/pull/265

**Comment by domenicbove** [comment]
This can be closed because pr 265 has been merged
