### ISSUE TITLE
Make ZooKeeper bind address configurable?

### ISSUE THREAD

**Issue by kongslund** [confluentinc/cp-ansible#263]
Should it be possible to specify the ZooKeeper bind address?

For a ZooKeeper cluster consisting of hosts with inventory names `zookeeper[1-3].foo.local`, on each host `/etc/kafka/zookeeper.properties` will currently look like this:
```
# Maintained by Ansible
...snip...
server.1=zookeeper1.foo.local:2888:3888
server.2=zookeeper2.foo.local:2888:3888
server.3=zookeeper3.foo.local:2888:3888
```

Which interface will Zookeeper bind to? Well, that depends on `/etc/hosts`.

It's customary for a host to have multiple (autogenerated) entries for its hostname in `/etc/hosts`, e.g.
```
...
127.0.1.1	zookeeper1.foo.local zookeeper1
192.168.62.100	zookeeper1.foo.local zookeeper1
```

When `127.0.1.1` is present, then I experience that ZooKeeper only binds to that interface:
```
root@zookeeper1:~# ss -nlt | grep 3888
LISTEN     0      50                           ::ffff:127.0.1.1:3888                                                   :::*
```

That means the other ZooKeeper instances can't communicate with it.

If `127.0.1.1` is not present, then `192.168.62.100` is used:
```
root@zookeeper1:~# ss -nlt | grep 3888
LISTEN     0      50                      ::ffff:192.168.62.100:3888                                                   :::*
```

I am not sure removing `127.0.1.1` from `/etc/hosts` is the right thing to do. Hence my question if it should be possible to specify the ZooKeeper bind address?

**Comment by kongslund** [comment]
As an addendum, I see that someone on StackOverflow [suggests](https://stackoverflow.com/a/30993130/37548) to specify 0.0.0.0 for the current node, e.g.

```
server.1=0.0.0.0:2888:3888
server.2=zookeeper2.foo.local:2888:3888
server.3=zookeeper3.foo.local:2888:3888
```

**Comment by JumaX** [comment]
Hi @kongslund thank you for your question.

Assuming I am understanding the question (apologies if I am missing something), this doesn't appear to be specific to CP-Ansible or even necessarily Zookeeper, but more about DNS resolution in Linux, Zookeeper just happens to be the application involved. 

In your example, I can see that you have the same hostname specified for two distinct IP addresses in your `/etc/hosts` including what I assume is meant to be the localhost address, this is somewhat unusual.  Generally I would expect the `/etc/hosts` to look as follows:

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
<ip address1>  hostname 
<ip address2>  hostname2
<ip address>  hostname3
```

I am going to assume that you want Zookeeper to listen over `192.168.62.100	zookeeper1.foo.local zookeeper1`, in which case your `/etc/hosts` file should look like:

```
127.0.1.1	localhost
192.168.62.100	zookeeper1.foo.local zookeeper1
```

You should also have additional entries in `/etc/hosts` for any other zookeeper nodes you plan to work with.  For example:

```
127.0.1.1	localhost
192.168.62.100	zookeeper1.foo.local zookeeper1
192.168.62.101  zookeeper2.foo.local zookeeper2
192.168.62.102  zookeeper3.foo.local zookeeper3 
```

The core issue appears to be that DNS mappings are not correct for the way you want to communicate on the network.

**Comment by domenicbove** [comment]
Looks like this is being addressed in this pr: https://github.com/confluentinc/cp-ansible/pull/253
Along with ZK security features

**Comment by JumaX** [comment]
@kongslund  Thanks for your patience on this, I've definitely learned something here about DNS resolution on Linux.  It appears that your DNS setup is valid and correct depending on the distribution, for example both Arch linux and Debian configure the `/etc/hosts` the way you have described above.  However RHEL/CentOS does not.   We are going to make this configurable and default to 0.0.0.0 so Zookeeper will listen on all interfaces by default.  Thread from the PR with the fix is here:  https://github.com/confluentinc/cp-ansible/pull/253#discussion_r414779291

**Comment by kongslund** [comment]
Thanks for giving it some thought.

Is #253 close to being approved? If not, could this be a separate PR?

**Comment by JumaX** [comment]
@kongslund It's actively being worked on, I suspect it will be merged soon.

**Comment by domenicbove** [comment]
Covering this issue with this pr: https://github.com/confluentinc/cp-ansible/pull/281

**Comment by domenicbove** [comment]
@kongslund this pr: https://github.com/confluentinc/cp-ansible/pull/281 has been merged into the 54x and 55x branches. You're going to want to set this property in your inventory file:
```
zookeeper_current_node_hostname: 0.0.0.0
```
Let us know how it goes, I'll probably close this in a few days if I don't hear back

**Comment by kongslund** [comment]
@domenicbove It works beautifully. Thanks! :)
