### ISSUE TITLE
Empty ssl_key_pass

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#274]
I am struggling using a custom ssl cert and key without a password.

If I understand it correctly the playbook is rekeying the key to pem format and if I do not set a password the final password will be `confluentkeystorestorepassword`.
If I do not set `ssl_key_password` the playbook will fail.
Would it work to set `ssl_key_password: null` or `ssl_key_password:""` 
Is furthermore possible to avoid the rekeying and setting no final password?

**Comment by domenicbove** [comment]
Hey, funny you ask because I just pushed functionality to the 550 branch that allows you to omit that password: https://github.com/confluentinc/cp-ansible/blob/5.5.0-post/roles/confluent.ssl/tasks/custom_certs.yml#L48

see the "when ssl_key_password is defined"

What branch are you on?

**Comment by domenicbove** [comment]
Nice use of the omit filter!

Can you put that into a PR? You are not the first person to request that feature

**Comment by Fobhep** [comment]
sure :)

**Comment by domenicbove** [comment]
Closing this one because this pr: https://github.com/confluentinc/cp-ansible/pull/275 is merged
