### ISSUE TITLE
Equalto Filter Jinja

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#279]
The equalto filter that is used in this repo comes with Jinja Version 2.8 - whereas a default CentOS 7 delivers currently only Jinja 2.7 via rpm.
Meaning there is no "clean" way to install 2.8.

Do you consider this a bug? Maybe one could ship the equalto filter for those "legacy" applications?

I reckon Centos7 is still quite spread.

**Comment by JumaX** [comment]
Hey @Fobhep, this is a really good catch, thanks for this! Let us do some investigation and figure out the best way forward.

**Comment by JumaX** [comment]
hey @Fobhep we've reverted that change in the following PR, should be corrected from here on out.  https://github.com/confluentinc/cp-ansible/pull/280

**Comment by Fobhep** [comment]
@JumaX cool - that should definitely fix it. thanks for the quick fix! :)
Shipping the equal filter yourself is not an option?

**Comment by domenicbove** [comment]
I didn't think it was worth the dev time, since I knew the old filter worked well
