### ISSUE TITLE
zookeeper_current_node_hostname: 0.0.0.0 makes nodes unable to work after restart

### ISSUE THREAD

**Issue by AntonSmolkov** [confluentinc/cp-ansible#287]
**Describe the issue**
Setting `zookeeper_current_node_hostname: 0.0.0.0`  in inventory makes nodes unable to work after restart. 
The setting was added with PR- https://github.com/confluentinc/cp-ansible/pull/281

**To Reproduce**
`systemctl restart confluent-zookeeper`

**Expected behaviour**
Node must survive restart, so does the cluster

**Additional context**
This is confirmed zookeeper bug - https://github.com/apache/zookeeper/pull/1254 
fixed in version 3.5.8 -https://github.com/apache/zookeeper/commit/800cc26a768fceda9ea42fe8121acf45fe781c57

Hower, according to the [table](https://docs.confluent.io/current/installation/versions-interoperability.html), latest version used by confluent platform is 3.5.7

**Comment by JumaX** [comment]
@AntonSmolkov Thanks for this!  We are looking at this internally currently and will come up with a solution shortly.  Rolling back that PR maybe the best option for the moment, will confirm.

**Comment by AntonSmolkov** [comment]
@kongslund be careful

**Comment by kongslund** [comment]
I'm actually using our external IP. I don't see a need for a rollback since 0.0.0.0 is not the default.

**Comment by kongslund** [comment]
To elaborate, I set `zookeeper_current_node_hostname` like this:

```
    zookeeper_current_node_hostname: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
```

**Comment by JumaX** [comment]
@AntonSmolkov @kongslund We are going to remove the example where we show you how to override this behaviour, as the default uses the Hostname/IP Address in the inventory file.  We will leave this issue open until a new version of Zookeeper is shipped.

**Comment by domenicbove** [comment]
Closing this because this is an issue with zookeeper not with cp-ansible. The default of zookeeper_current_node_hostname is the inventory_hostname, so there is no bug
