### ISSUE TITLE
Switch from SCRAM-SHA-256 to SCRAM-SHA-512

### ISSUE THREAD

**Issue by nbisson** [confluentinc/cp-ansible#298]
Hi,

First, thank you for creating this project.
The project implements SCRAM-SHA-256 but I would like to use SCRAM-SHA-512 instead.
Would it be possible to implement a switch to replace it ?
Thank you in advance.

**Comment by JumaX** [comment]
Hello @nbisson thanks for the question.  

Right now we only support SCRAM-SHA-256 in this repo, and unfortunately there currently isn't an easy way to override this.

We will add this to our roadmap and add it in a future release.  Most likely it will end up being an overridable variable.  We will update this thread once it's been implemented.

**Comment by domenicbove** [comment]
Hi @nbisson I just made the change 256->512 in the master branch with this pr: https://github.com/confluentinc/cp-ansible/pull/313

The plan is to release the master branch when confluent platform 6.0 is released later this summer. For the time being you can use that branch and it still installs 5.0 if you would like this scram change (and all of our latest and greatest features). We are getting out of the habit of making feature changes on already released versions so you we have no plans of making that change on 5.5.0-post branch, and you will have to wait until master becomes 6.0.0-post
