### ISSUE TITLE
Loop is deprecated

### ISSUE THREAD

**Issue by jcustenborder** [confluentinc/cp-ansible#32]
fatal: [broker-1.example.com]: FAILED! => {"msg": "Unexpected failure in finding the lookup named '{{kafka.broker.datadir}}' in the available lookup plugins"}

Fixed it by using with_items

**Comment by cotedm** [comment]
another person hit this https://github.com/confluentinc/cp-ansible/issues/28

I guess ansible 2.5 isn't that well adopted yet so I will change this so it works before 2.5, but still recommend 2.5 with the playbook
