### ISSUE TITLE
Kafka Broker doesn't restart on reboot

### ISSUE THREAD

**Issue by linsomniac** [confluentinc/cp-ansible#321]
**Describe the issue**
The confluent.kafka_broker role triggers a handler to start the kafka-broker, but it never does an "enabled: true".  I was setting it up with 5.5.0, but it looks like it's similar not enabled in default.  If there is no expectation that the broker is enabled, perhaps an "enabled: false" and/or a comment about it?  Or a configurable in the all.yml?

**To Reproduce**
Set up a kafka broker cluster and reboot members.

**Expected behaviour**
Kafka broker comes up after a power outage or reboot.

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - CP-Ansible Branch: 5.5.0-post, default
 - Ansible Version Ansible 2.9.2 and 2.9.9

**Comment by domenicbove** [comment]
Wow that is a nice catch! There should be an `enabled: true` there, all the other components have it

**Comment by domenicbove** [comment]
resolved with this pr: https://github.com/confluentinc/cp-ansible/pull/322

**Comment by linsomniac** [comment]
Oops, while I was testing my PR, you got this closed.  Thanks, I'll go close the PR!
