### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by GuyIEX** [confluentinc/cp-ansible#353]
I have a few changes to the playbooks that my customers have asked for. I would love to contribute them back, but I was unsure if these would be of interest to the maintainers/larger community. In no particular order:

1. Install into a target directory (default: `/opt/confluent`) using an archive instead of repository-based installs. This also creates configuration files in the target directory (default: `/opt/confluent/etc`) and creates systemd services pointing at these binaries and configs
1. Provide the ability to skip (using `--skip-tags` and some variables) certain operations. For example, skip any sysctl/systemd operations for environments that don't support them or skip apt/yum operations if the environment is already prepared.
1. The main environment I've been working in is docker-compose using ansible-pull. I can provide documentation or a repo showing this working, but it's dependent on the ability to skip sysctl/systemd operations.

These enhancements were designed for "offline" deployments where the nodes are not connected to the open internet and administrators don't generally have root access once a node is in production. I use docker-compose to demonstrate various configurations without the overhead of spinning up potentially a few VMs.

I have been working with the `5.5.1-post` branch, but these enhancements could be done against whichever branch(es) need it, I would just need some direction.

Thanks!

Edit: I cannot add the Question label per the Contributions documentation.

**Comment by JumaX** [comment]
Hi @GuyIEX 

Thanks for the question/offer to contribute, it's very much appreciated.

Let's step through this point by point:

1. We've had this request before, from some of our commercial customers and it's something we've got on our roadmap for the future.  If you've already developed this work, we would love to have the contribution.

I would suggest you review the 6.0.x branch as that is our current development branch for the next release, so ideally we would like to see a PR against, it for this work.  5.5.1 is considered a stable branch at this time and thus we don't want to add new functionality.  We only want to apply bug fixes.

Let me know if you have any questions about the 6.0.x branch.

2. I like the idea of --skip-tags, however I think it's really dependent on what they are being applied to.  For example, you mention skipping operations for SystemD, which I don't think is something we want to support.  We currently only support OS's which rely on SystemD, as older Linux Distros that still use init are generally end of life/going away in the next few months. 

My suggestion would be to generate a list of places where you would want the skip functionality and we can validate what makes sense for this repo.

3. We actually have built in docker scenario testing in our repository using molecule.  I would recommend using that.  It supports full systemD functionality, and we already have a large number of scenarios setup.  

Documentation is here: https://github.com/confluentinc/cp-ansible/blob/5.5.1-post/HOW_TO_TEST.md

Note: I will be updating this further for the 6.0.x release.

**Comment by GuyIEX** [comment]
@JumaX thanks for the feedback!

1. I can isolate those changes and get a PR against 6.0.x submitted by (hopefully) tomorrow. After I isolate, comments and test I can create the issue to submit the PR against too.
2. I'll have to put this one on the back burner because the main reason I'm skipping things is because SystemD isn't well supported in CentOS 7 images. However, I'm digging into molecule and running those tests so it may be a moot point.
3. I believe molecule is a testing environment and what I was doing is more of a demonstration environment for various capabilities. Those demonstration environments were also used for some rapid prototyping. Not specifically Ansible related, but it did demonstrate how to use something like ansible-pull in a constrained environment. I will hold off on this one too.

**Comment by JumaX** [comment]
@GuyIEX Understood.  

Regarding point 2, can you confirm what you mean by systemD not being supported in CentOS 7 images?  I ask because its the default for CentOS 7, and the images we test on, when not testing for OS specific functionality is primarily is CentOS 7.  Curious to know what I am missing.

**Comment by GuyIEX** [comment]
Sure. A good discussion is is captured [here](https://linuxacademy.com/community/show/21629-docker-failed-to-get-dbus-connection-operation-not-permitted/) on the use of SystemD within containers. However, these limitations can be overcome with some Dockerfile magic as documented at https://hub.docker.com/_/centos (look for the section named "Systemd integration"). I also believe podman overcomes some of these limitations as discussed [here](https://developers.redhat.com/blog/2019/04/24/how-to-run-systemd-in-a-container/).

**Comment by domenicbove** [comment]
Hey @GuyIEX ! It's super cool that you have come up with a new installation method. Some of our customers request that our playbooks do not run as root which you need to yum installs. And I thought as well managing services. Does your branch run as root?

Regarding systemd in containers, it is possible, and the ppl who designed molecule had to sort that out fairly early on. Here are the docs: https://molecule.readthedocs.io/en/latest/examples.html#systemd-container

In fact a lot of our testing in on centos7 containers.

Im curious what your motivation is? Is the end goal to run the platform in containers? We have prebuilt images with our packages in them already (I can point you to our cp-demos repo). And if you were to use those, then the only piece you would need from cp-ansible is to get the properties written, which would be pretty easy in the 6.0.x branch with a tag or conditional

**Comment by GuyIEX** [comment]
Hi @domenicbove ! The branch does run as root because it creates SystemD services if they aren't found.

My motivation is being able to put together a package (in this case it's a docker-compose environment) that clients can use as a reference when they are able to make changes to their dev/test/prod environments. For example, during my last engagement I put together a docker-compose environment showing the client what changes they would need to make to support SSL authentication among the services, how that tied in with their current architecture and documentation they could use to administer it once established. They also wanted to use Ansible for deployments, but were hindered by 1) not having root access to the nodes once they were deployed 2) having automated SSH login methods (keys, sshpass, etc) completely disabled, even in dev and 3) not allowing the nodes to access the internet once deployed. So, we settled on them being able to use ansible-pull. I put together another docker-compose environment showing them the interactions needed for ansible-pull to work.

I have run into a problem in porting this to the 6.0.x branch. Specifically, I look for a SystemD service and if it doesn't exist then I create a new file. However, if it does exist then I don't do anything with it. That leads to a problem where CP is already deployed on a node as the old service file will most likely point to the wrong binary and config files. I think there are 3 options, but I don't know which is more in line with your current methodology.

1. Add a property to enable overwriting the service file
1. Always overwrite the service file (I think this is the appropriate answer)
1. Current behavior of only writing the service file if it doesn't exist

Thoughts?

**Comment by domenicbove** [comment]
There's a lot in that message! I'll try and respond to everything!

1) If you are looking to demo confluent platform in a docker containers, then we already have multiple configurations you can spin up with molecule. Like if you want to show customers mtls on rhel then you would run:

```
cd roles/confluent.test
molecule converge -s mtls-rhel
docker ps
docker exec -it <container-name> /bin/bash
molecule destroy -s mtls-rhel
```

There are a bunch of scenarios ready to go! Now going beyond demos, you bring up some good customer use cases and each should most likely be solved in their own PRs. 

1) No root access
This one we get a lot. Without root you can't do yum install... The workaround is the tar based installation: https://docs.confluent.io/current/installation/installing_cp/zip-tar.html
Which will get you everything, but then you are still out of luck for managing the services with systemd... Which I think is the defacto standard for managing services, so I usually stop there... I would not recommend running long running services with a background bash command :)

2) Not having ssh
This is essentially how ansible functions. There are other connection options that maybe they can explore. I'm missing how you can get around not having ssh (or an alternative) and still want to use ansible.

3) No outside internet access
We actually have a solution for this, which entails putting our packages in your customer's repo server and providing a .repo file
You'll also have to host jolokia's jar in a webserver accessible to the hosts.

Can you explain how ansible-pull solve these problems? https://docs.ansible.com/ansible/latest/cli/ansible-pull.html

Is the plan to run each component in a container on each vm? Honestly, there is merit in that solution, build the images in a place with internet access and then you can distribute images pretty easily in tar format (Or better yet use the images we already offer!).

And finally if your issue is that your docker compose set up does not allow for systemd service, there is a way to get docker containers to work w systemd, I know this bc our molecule containers use systemd

**Comment by GuyIEX** [comment]
Sorry for the over-communication. I'll try to keep this brief.

I'm currently looking into molecule. It's on my list of technologies to research, I just hadn't got that far yet ;)

1. No root access - Yes, they install via a tarball. The enhancements I'll submit against the 6.0.x branch do just this, just they also create SystemD services. I believe the customer currently uses their own custom scripts to manage these processes.
2. Not having SSH - This is solved by ansible-pull. Using this mode of ansible you have a Git server (or some other vcs) that the node will clone a repo containing playbooks and other resources from then run locally. So, as an administrator you need to connect to the node to be staged and install/run ansible-pull pointing it at a vcs.
3. No outside internet access - We explored this solution, but thought the team managing the repo servers would have a problem with it (internal conflicts and all).

Hopefully I explained how ansible-pull solves (2) above.

The plan is to run multiple VMs with multiple services on each. What I as the consultant who doesn't have access to these environments was trying to provide is a way for them to understand how to transition to new configurations through a emonstrative docker-compose environment that mirrors their development environment. Unfortunately ansible-pull was not part of what I provided them due to time constraints.

I honestly was unaware of the ability to run SystemD in a CentOS 7 container because I failed to RTFM the docker hub page.

**Comment by domenicbove** [comment]
Thanks for the clarification!

1) No root access- I would prefer if the solution was all encompassing. Meaning it 
- installed the tar ball (you have this)
- set up a systemd service that can run as a _configurable_ non root user: https://vic.demuzere.be/articles/using-systemd-user-units/
- and starts the service/ passes health checks
But if we accomplish this. Many people will be happy! We have to make the link for the tar ball configurable bc some customers dont have outside internet access (ie theyll host the tarball themselves)

2) Not having ssh... Wait so ansible-pull pulls the cp-ansible source code onto a single node, this node has ansible on it, but cannot connect to any other nodes, and then it runs the playbook only modifying itself... meaning you have to go one host at a time? This can't be right :)
If you are saying ansible pull is just a way of distributing cp-ansible to an ansible control node which **has connectivity** to other nodes, then go right ahead! some customers tar up our repo and scp it around.

3) Its actually pretty easy to turn the ansible control node into a webserver using python simple server. But im still unsure about number 2

All in all I like where this discussion is going w #1 !

**Comment by GuyIEX** [comment]
The way I implemented the SystemD service files they will use whatever the appropriate <service>_user and <service>_group as defined by the variables/properties. I also documented all the new properties in `VARIABLES.md`. I'll get that issue and PR created right away.

**Comment by JumaX** [comment]
@GuyIEX Going to close this one out due to the merge of the tarball installation work.
