### ISSUE TITLE
Document changes to Ansible new release

### ISSUE THREAD

**Issue by jaywojick** [confluentinc/cp-ansible#354]
Customer is asking to add a README that includes the New features for the latest CP-Ansible release.

**Comment by JumaX** [comment]
Hi @jaywojick,

Thanks for the request.

We have an internal request for this as well, in our current backlog.  It's something we are looking into.  In the meantime the release should generally match what's in the platform release notes:  https://docs.confluent.io/current/release-notes/index.html

**Comment by jaywojick** [comment]
Thanks for the update.

**Comment by domenicbove** [comment]
@jaywojick  we have settled on putting our release notes here: https://docs.confluent.io/current/release-notes/index.html#ansible
And will continue to update those docs on every release.
