### ISSUE TITLE
Missing part in RBAC documentation

### ISSUE THREAD

**Issue by rsaggino** [confluentinc/cp-ansible#359]
**Describe the issue**
While configuring a Kerberized cluster, with RBAC enabled, you might see issues related to "kafka_broker_principal" variable missing from the hosts file.
The variable is undocumented and also missing from the example host file.

**Environment (please complete the following information):**
 - OS: RHEL 7.6
 - CP-Ansible Branch: 5.5.0-post

**Additional context**
Can be fixed by adding "kafka_broker_principal: <kerberos_service_name>" to the kafka_broker variables.

**Comment by JumaX** [comment]
Hi @rsaggino,

Thanks for the report.  Can you confirm exactly the error you received (please include the log snippet) and the exact steps taken to reproduce.

The reason I ask, is that you shouldn't have to specify that variable at all.  In fact we have a test written in molecule which sets up RBAC with Kerberos and doesn't require setting that variable here: 

https://github.com/confluentinc/cp-ansible/tree/5.5.0-post/roles/confluent.test/molecule/rbac-kerberos-debian

You can actually see the code where we set that principal for you here at lines 12 through 15:

https://github.com/confluentinc/cp-ansible/blob/5.5.0-post/roles/confluent.kafka_broker/tasks/set_principal.yml

So I suspect there is actually some other issue happening here that maybe leading to the problem you are seeing.

**Comment by JumaX** [comment]
@rsaggino I just wanted to follow up and see how you are making out with this issue?  Provided I don't hear back from you by Friday, I will go ahead and close it out.

**Comment by rsaggino** [comment]
Seems to be working, don't know what was wrong before. Thanks
