### ISSUE TITLE
Connectors are unarchived and do not necessarily have the correct permissions

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#366]
Deploying a new connector via archive does not necessarily set the correct permission automatically.
When you have a strong umask for your ansibe user, you might run into issues.

suggested solution:
Add concret permissions in the unarchive task.

**Comment by domenicbove** [comment]
Is this what you are looking for: https://github.com/confluentinc/cp-ansible/pull/368

**Comment by domenicbove** [comment]
Wow I just saw your PR lol!
I actually assumed you knew the fix to this as I was doing it @Fobhep

**Comment by Fobhep** [comment]
oha sorry :D

**Comment by domenicbove** [comment]
Mine was second, don't change your process!

**Comment by domenicbove** [comment]
@Fobhep this can be closed right? I merged your pr up thru 5.5.1 and higher branches
