### ISSUE TITLE
Allow complete deactivion of repo deployment

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#369]
For certain customer "offline" installations it would be helpful to deactive any creation of confluent repository files, since everything is already mirrored towards a Satellite or orcharhino.

I propose a "no_repository" flag in hosts.yml that can be included in the common tasks for each OS

**Comment by JumaX** [comment]
@Fobhep Thanks for the suggestion.  Can you clarify further?  Do you mean that the packages are already present on the OS? I ask because typically a satellite will still involve pulling the packages from the satellite and installing them locally which we can do already via the custom repo functionality.  So I am not completely clear on the use case described here.

**Comment by Fobhep** [comment]
of course - let me try to explain better.
So eg at the customer I am currently at (and the previous one as well), all servers are deployed via Satellite and corresponding hostgroups, so they have already all repos and repofiles included they need for confluent platform.
We cannot break this workflow, since different teams are in charge of base provisioning and middleware.
Currently I simply removed the part that deploys repos. I am wondering if allowing that generally would be an useful feature for more people. Of course you could probably also deploy an "empty" custom repo file as well :thinking: 
Let me know if I explain it still better

**Comment by domenicbove** [comment]
@Fobhep I think this is a great idea. Im thinking we could have a variable like `repository_option: none/confluent/custom` which defaults to confluent. This is to replace the custom_repo variable. Well have to think on backwards compatibility... 

I'm not that satisfied with the variable name haha, if you come up with something better LMK.

Would you like to create the PR? I don't want to jump the gun like last time, but I can do it also.

**Comment by Fobhep** [comment]
@domenicbove great :) I can do that probably monday or tuesday - if you are up for it before - go for it :)

**Comment by domenicbove** [comment]
@Fobhep I have some bandwidth! I'll work on it today and include you in the PR. Since I'm not considering this a bug, I'm planning to make the PR into 6.0.x branch which is our 6.0.0 dev branch. Hope that's ok

**Comment by domenicbove** [comment]
@Fobhep can you review this: https://github.com/confluentinc/cp-ansible/pull/370
For some reason I can't add you as a reviewer on the PR. 

Essentially you set `repository_configuration: none` to get what you are seeking with this issue... Java installation must happen though

**Comment by domenicbove** [comment]
Closing, as https://github.com/confluentinc/cp-ansible/pull/370 has been merged. Will be released with 6.0.0!
