### ISSUE TITLE
ksql start need KSQL_OPTS="-Djava.io.tmpdir=/vdb/state" option for rocksdb to work

### ISSUE THREAD

**Issue by nhe150** [confluentinc/cp-ansible#397]
other wise when run any group by it will claims:
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.DBOptions
Caused by: Could not initialize class org.rocksdb.DBOptions
Query terminated

did i forget some options or this is indeed an issue?

**Comment by domenicbove** [comment]
Hey @nhe150 interesting catch! Is this documented anywhere in ksql's docs?

A simple work around while this gets investigated is to add this to inventory
```
ksql_custom_java_args: "-Djava.io.tmpdir=/vdb/state"
```

**Comment by nhe150** [comment]
that is great. and ksql should setup the /vdb/state directory since it is in role of control center, i have to run control center on same machine just to set up /vdb/state. seems need to copy all the ROCKS_DB_PATH  into ksql also?

**Comment by nhe150** [comment]
@domenicbove , here is the issue report 
https://github.com/confluentinc/ksql/issues/1332

**Comment by domenicbove** [comment]
I've created this PR: https://github.com/confluentinc/cp-ansible/pull/398/files for this, but now I am wondering about the default behavior. In the solution right now, no rocksdb directory will be created/configured unless you set the `ksql_rocksdb_path` variable.

Is ksqldb broken without that env var set? Should the default behavior be to create a directory always? And if so what is a good default directory?

@nhe150

**Comment by nhe150** [comment]
current ksqlDB will be broken exactly. the pr is must... :)

**Comment by nhe150** [comment]
Great.

**Comment by domenicbove** [comment]
@nhe150 I just merged https://github.com/confluentinc/cp-ansible/pull/398
The fix is now in the 550 and higher branches. Use the `ksql_rocksdb_path` variable. Can you let me know if the fix works on your end and then we can close this

**Comment by JumaX** [comment]
Closing this out, due to fix being shipped and lack of response.
