### ISSUE TITLE
Documentation Shortcomings

### ISSUE THREAD

**Issue by TheNedster** [confluentinc/cp-ansible#41]
Hi,
 The following needs to be updated:

Confluent Platform 4.1 or higher
Ansible 2.5.x or higher (on control node)
Confluent Platform Ansible playbooks
passwordless ssh between all hosts
sudo access for ssh user for all hosts
**Redhat Enterprise or Centos 7 only**

The current play list supports RHEL and Centos NOT Debian or Ubuntu which I discovered after creating 7 Ubuntu VMs. I note that this is listed as a future enhancement but that not would not be apparent to those who read the Blog post and then the Documentation.

**Comment by cotedm** [comment]
linking #10 here. Adding the support for debian based linux should be pretty straightforward, so I'd rather just add it then document a limitation, then remove that limitation shortly after. If this lingers, we can doc it, but I don't anticipate that happening.
