### ISSUE TITLE
TASK [confluent.ssl_CA : copy ssl related files to local ansible host]

### ISSUE THREAD

**Issue by TheNedster** [confluentinc/cp-ansible#42]
This fails as the /var/ssl/private does not exist on the target node. I manually created the directories and the  task passed.

**Comment by cotedm** [comment]
Part of [the playbook](https://github.com/confluentinc/cp-ansible/blob/master/roles/confluent.common/tasks/ssl_certs.yml) already creates this directory. Can you clarify how you were running? Do you have more output that you can show demonstrating the error?

**Comment by TheNedster** [comment]
In check mode @cotedm

**Comment by cotedm** [comment]
Ah yes @TheNedster then this will be also better in when #29 is complete. I'll add it there. Basically it can't make filesystem changes in check mode so this won't work in check mode. #29 will break down things so these dry runs will work properly.
