### ISSUE TITLE
Upgrading from 5.5.2-post --> 6.0.0-post fails due to confluent-kafka-2.12-5.5.2-1.noarch conflicts with confluent-kafka-6.0.0-1.noarch

### ISSUE THREAD

**Issue by aglahe** [confluentinc/cp-ansible#421]
**Describe the issue**
Following [upgrade docs](https://docs.confluent.io/current/installation/cp-ansible/ansible-upgrade.html), when starting the upgrade, doing upgrade_zookeeper.yml,  from 5.5.1 or 5.5.2 on Centos 7 to 6.0.0, there is a rpm conflict between confluent-kafka-2.12-5.5.2-1.noarch & confluent-kafka-6.0.0-1.noarch

This can be seen outside of cp-ansible upgrade_zookeeper.yml as well, doing a simple `yum upgrade`: 

_sudo yum install confluent-kafka
Resolving Dependencies
--> Running transaction check
---> Package confluent-kafka.noarch 0:6.0.0-1 will be installed
--> Processing Conflict: confluent-kafka-2.12-5.5.1-1.noarch conflicts kafka
--> Processing Conflict: confluent-kafka-6.0.0-1.noarch conflicts kafka
--> Finished Dependency Resolution
Error: confluent-kafka conflicts with confluent-kafka-2.12-5.5.1-1.noarch
Error: confluent-kafka-2.12 conflicts with confluent-kafka-6.0.0-1.noarch
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest_

**To Reproduce**
1. git clone cp-ansible
2. git checkout 5.5.2-post
3. Use cp-ansible to 'install' 5.5.x zookeeper and brokers
4. git checkout 6.0.0-post 
5. upgrade zookeeper: ansible-playbook -i hosts.yml upgrade_zookeeper.yml

**Expected behaviour**
upgrade zookeeper should remove confluent-kafka-2.12-XXXX in order to install the new confluent-kafka-6.0.0-1 since it conflicts with 6.0.0

**Inventory File**
Nothing crazy...can reproduce using simple inventory file.

**Logs**
TASK [Install the Packages - Red Hat] **********************************************************************************************************************************************************************************************************************************************************************************************************************************
Friday 02 October 2020  09:06:38 -0400 (0:00:00.107)       0:01:01.734 ********
ok: [x.y.z] => (item=confluent-common)
ok: [x.y.z] => (item=confluent-rest-utils)
ok: [x.y.z] => (item=confluent-metadata-service)
ok: [x.y.z] => (item=confluent-ce-kafka-http-server)
ok: [x.y.z] => (item=confluent-kafka-rest)
ok: [x.y.z] => (item=confluent-server-rest)
ok: [x.y.z] => (item=confluent-telemetry)
failed: [x.y.z] (item=confluent-kafka) => {"ansible_loop_var": "item", "changed": true, "changes": {"installed": ["confluent-kafka-6.0.0-1"], "updated": []}, "item": "confluent-kafka", "msg": "Error: confluent-kafka-2.12 conflicts with confluent-kafka-6.0.0-1.noarch\nError: confluent-kafka conflicts with confluent-kafka-2.12-5.5.2-1.noarch\n", "rc": 1, "results": ["Resolving Dependencies\n--> Running transaction check\n---> Package confluent-kafka.noarch 0:6.0.0-1 will be installed\n--> Processing Conflict: confluent-kafka-2.12-5.5.2-1.noarch conflicts kafka\n--> Processing Conflict: confluent-kafka-6.0.0-1.noarch conflicts kafka\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}

**Environment (please complete the following information):**
 - OS: Centos 7.7
 - CP-Ansible Branch: 5.5.2-post & 6.0.0-post
 - Ansible Version Ansible 2.9.0

**Comment by JumaX** [comment]
Hey @aglahe thanks for the report.  I will try to reproduce this shortly and come back with next steps.

**Comment by JumaX** [comment]
@aglahe Thanks again for the report.  We just merged in the fix.  Apologies again for hitting this, let us know if you run into any further issues. https://github.com/confluentinc/cp-ansible/pull/422

**Comment by aglahe** [comment]
Awesome!  Thanks everyone.
