### ISSUE TITLE
Deprecated attribute used when creating keystore for self-signed certs

### ISSUE THREAD

**Issue by gitfrog0** [confluentinc/cp-ansible#426]
In the file /roles/confluent.ssl/tasks/self_signed_certs.yml, the block:
```
- name: Create Keystore
  shell: |
    keytool -genkey -noprompt \
      -storetype pkcs12 \
      -keyalg RSA -keysize 2048 \
      -alias {{inventory_hostname}} \
      -dname "CN={{inventory_hostname}},OU=TEST,O=CONFLUENT,L=PaloAlto,S=Ca,C=US" \
      -ext "SAN={{hostnames | cert_extension}}" \
      -keystore {{keystore_path}} \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}} {{extra_args}}
```
uses `-genkey`, this has been replaced with `-genkeypair` in newer Oracle documentation.
See https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html for more info.

**Comment by JumaX** [comment]
@gitfrog0 Thanks for the heads up, will look at getting a PR in shortly to correct this.

**Comment by JumaX** [comment]
@gitfrog0 We just pushed PR 430 into the 6.0.0-post branch which corrects the issue.  Thanks again for the feedback.
