### ISSUE TITLE
TASK [confluent.common : Install the Confluent Platform]

### ISSUE THREAD

**Issue by TheNedster** [confluentinc/cp-ansible#43]
Getting this error:
fatal: [server1.westus2.cloudapp.azure.com]: FAILED! => {"changed": false, "msg": "No package matching 'confluent-platform-2.11' found available, installed or updated", "rc": 126, "results": ["No package matching 'confluent-platform-2.11' found available, installed or updated"]}

**Comment by TheNedster** [comment]
Got around this by installing the repo on four of the nodes

**Comment by cotedm** [comment]
part of the playbook is [installing the repo](https://github.com/confluentinc/cp-ansible/blob/master/roles/confluent.common/tasks/redhat.yml), can you clarify how you were running this? What version did you run? What commands did you use?

**Comment by cricket007** [comment]
Was that a non Redhat host?

**Comment by TheNedster** [comment]
It is RHEL 7 on Azure

**Comment by TheNedster** [comment]
> part of the playbook is installing the repo, can you clarify how you were running this? What version did you run? What commands did you use?

The version of the playbook was taken at the beginning of the last week. I ended up running the play book with the check option until I had uncovered all the problems. I ended up having to add the repo details to all the nodes that required it. The script then ran it installed Confluent Enterprise. I checked all the nodes with CLI as it was installed but not running.

**Comment by cotedm** [comment]
yes, --check will keep anything from being changed on disk, so the repo won't install that way. #29 and #11 are to make this a little more transparent. If you had run the without --check, this would not have happened. Since we have a play to make the dry runs work better, I'll close this one. Thanks for bringing it to our attention!

**Comment by abhishek-sehgal954** [comment]
Can anyone guide me how to install the confluent version 4.1.1
I changed roles/confluent.common/defaults/main.yml to 

`zookeeper:
  config:
    clientPort: 2181
broker:
  config:
    port: 9092
confluent:
  package_name: confluent-platform-2.11
  support:
    customer_id: anonymous
    metrics_enabled: true
  repository:
    debian:
      key_url: https://packages.confluent.io/deb/4.1/archive.key
      repository: "deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main"
    redhat:
      main:
        baseurl: https://packages.confluent.io/rpm/4.1
        gpgcheck: 1
        gpgkey: https://packages.confluent.io/rpm/4.1/archive.key
        enabled: 1
      dist:
        baseurl: https://packages.confluent.io/rpm/4.1/7
        gpgcheck: 1
        gpgkey:  https://packages.confluent.io/rpm/4.1/archive.key
        enabled: 1
`
but i am able to install version 4.1.2

**Comment by cricket007** [comment]
AFAIK, all Confluent repos point at the latest patch release.

If, for whatever reason, you decide you need a potentially buggier version of the platform, you're welcome to grab a tarball from here and install manually https://www.confluent.io/previous-versions/
