### ISSUE TITLE
Hash behaviour to be deprecated

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#458]
Ansible will remove any `hash_behavior` config from version 2.13 and deprecated it in 2.10.
Since many customers are currently already updating to 2.10 maybe there should be a notion somehwere that the deprecation warning is not an issue for the moment.

For the future probably the playbooks need to make use of `combine` as described here:

https://www.reddit.com/r/ansible/comments/dhsavl/hash_behaviour_deprecated_for_the_210_release/

**Comment by JumaX** [comment]
@Fobhep Thanks for reaching out.  We are aware of the removal/deprecation, and have an internal JIRA to track this already.  We actually have already documented that we rely on hash merging in the following documentation in the `Important` section: https://docs.confluent.io/current/installation/cp-ansible/ansible-install.html#install-cp-with-ansible-playbooks

**Comment by Fobhep** [comment]
perfect. How do you feel about adding
```
deprecation_warnings=false
```

to the shipped ansible.cfg? It won't influence the global Ansible Settings and should be fine in terms of compability, since you test your cfg file as well.
I am actually but undecided :thinking:

**Comment by JumaX** [comment]
@Fobhep we are hesitant to remove deprecation warnings, as it's an all or nothing setting.  We want to make sure we don't miss any other deprecation warnings on future development we conduct.  If we could just filter out the hash merging warnings, we would be okay with that, but it's currently not possible.

**Comment by Fobhep** [comment]
@JumaX that makes perfect sense. Thanks for the information and please feel free to close this issue.
