### ISSUE TITLE
Keystores with more than one cert

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#462]
I am using the approach of self provided key- and truststores and have a keystore that includes more than one certificate. For this scenario the ssl-role extracts like this:

```yml
    - name: Convert Keystore to Pem Format
      shell: |
        keytool -noprompt -importkeystore \
          -srckeystore {{keystore_path}} \
          -srcstorepass {{keystore_storepass}} \
          -destkeystore /var/ssl/private/generation/{{service_name}}.p12 \
          -deststoretype PKCS12 \
          -deststorepass {{keystore_storepass}} \
          -destkeypass {{keystore_storepass}} {{extra_args}}
```

However this fails, since the keystore contains more than one certificate and does not know which to use. My fix is currently to add an additional parameter `-srcalias {{inventory_hostname}}` to the keytool command.

I did not yet get to test, whether that would work also for keystores that contain only one certificate, but I assume it might. Do you see this as a possible improvement for upstream? :)

**Comment by domenicbove** [comment]
Hey @Fobhep that actually makes a lot of sense. We can definitely add a new variable, but we should not make it a required. It could look like this:

```
    - name: Convert Keystore to Pem Format
      shell: |
        keytool -noprompt -importkeystore \
          -srckeystore {{keystore_path}} \
          -srcstorepass {{keystore_storepass}}{% if keystore_alias is defined %}  -srcalias {{keystore_alias}} {% endif %} \
          -destkeystore /var/ssl/private/generation/{{service_name}}.p12 \
          -deststoretype PKCS12 \
          -deststorepass {{keystore_storepass}} \
          -destkeypass {{keystore_storepass}} {{extra_args}}
```

Or do two tasks with a `when: keystore_alias is defined` ... Two tasks take longer though.

**Comment by domenicbove** [comment]
Another thing worth mentioning is that the exporting of certs really is only required when a component has an MTLS enabled rest endpoint. We should really have a new input variable for the ssl role, maybe called `export_certs` so that these tasks can be skipped

**Comment by Fobhep** [comment]
I drafted a PR :) Feel free to comment

**Comment by Fobhep** [comment]
@JumaX I think we close this?
