### ISSUE TITLE
we don't have control over broker and zookeeper, somehow we want to monitor ksqlDB all component through jmx, what is the ansible option for that?

### ISSUE THREAD

**Issue by nhe150** [confluentinc/cp-ansible#465]
**For Confluent Enterprise Support customers, we would strongly advise you to open a Support ticket which will be addressed within your Support contract SLA at ```https://support.confluent.io```**

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Inventory File**
proxy_env: need to add comments about JMX port 
    
Please provide your inventory file in order to aid in the investigation.

**Logs**
Please provide the output of the ```-vvv``` switch from Ansible with the failed log snippet. Please also provide the logs of the specific component which has failed.  If multiple attempts to run have been made, please provide the start and stop time of the component if known.

**Environment (please complete the following information):**
 - OS: [e.g. RHEL 7.6]
 - CP-Ansible Branch: [5.5.0-post]
 - Ansible Version [e.g. ansible 2.9.6]

**Additional context**

**Comment by domenicbove** [comment]
@nhe150 Can you fix your initial comment and fill in the template? I'm not sure what you are looking for based off of the title

**Comment by nhe150** [comment]
cp-ansible seems to enble jmx need to do 

all.yml  enable proxy can be done by turn on 

host.yml

proxy_env:
   JMX_PORT: 9999

we will give a try and see if it will do

**Comment by JumaX** [comment]
@nhe150 Apologies but it's still not completely clear what you are trying to do.  Please fill in the template as requested.

Regarding JMX, it's enabled by default and we allow both Jolokia (default option) and Prometheus agents for monitoring it.

**Comment by JumaX** [comment]
@nhe150 since we haven't heard back from you in some time, I am going to go ahead and close this issue out.  Please open a new issue and fill in the template should you have any further questions.
