### ISSUE TITLE
Adding (or Removing) Brokers/Zookeepers to (or from) an existing cluster?

### ISSUE THREAD

**Issue by aglahe** [confluentinc/cp-ansible#477]
This isn't a bug..but, also not sure if this is a feature request. 

If we have an existing cluster...brokers and zookeepers...if we want to add more of either (or each)..after updating the hosts/inventory do we run all.yml again?

1.  If it is adding zookeepers, say going from 3 --> 5, if we run all.yml...will the zookeeper.conf get updated with the proper ids?
2. For adding brokers, will it also update the server.properties file with all the appropriate ids?

Now imagine going in reverse..scaling down either brokers/zookeepers...remove them from the hosts/inventory file..do we run all.yml?  And will the 1. & 2. above happen...in reverse?

**Comment by JumaX** [comment]
Hello @aglahe thanks for the question.  

**We currently do not support updating clusters with these playbooks, they are for greenfield installs only.**  

That being said, you can add additional hosts, you would just update the inventory file (your hosts file) with the addition brokers/zookeepers and run the playbook again.  Understand, this will most likely lead to an outage if this is a prod environment as we don't take into account rolling the components in a staged way when doing the install.  As in, it's very possible that all of your zookeepers/brokers will be restarted at the same time, thus you would want a maintenance window for doing such work.

You shouldn't have to update any of the config files manually, they should get populated with the new settings automatically.

We do not support scaling down the cluster at this time.  If you remove components from the inventory, they will not be changed however your other remaining components will be.  This could lead to inconsistency in the environment, so we do not recommend this.  We would recommend manually decommissioning any old hosts first, and then running the playbook again with the new settings, with the previous understanding that we do not support updating clusters in a production safe way currently.

We do have it on our roadmap to better support day 2 operations (updating configs) as well as to support uninstall and general reconfiguration, however this is a ways off, as there are a lot of variables at play to get this working in a reliable and scalable way.
