### ISSUE TITLE
Ubuntu Installation steps missing

### ISSUE THREAD

**Issue by viveknangal** [confluentinc/cp-ansible#49]
Team - Please suggest is it only Redhat variants OS are supported by these Ansible scripts as I couldn't find the installation steps for Ubuntu/Debian specific platforms.

**Comment by cotedm** [comment]
@viveknangal the debian based linux install is in this pull request https://github.com/confluentinc/cp-ansible/pull/47

It should be merged in the next day or so. If you are willing to review, please do add comments over there.
