### ISSUE TITLE
Better ansible.cfg

### ISSUE THREAD

**Issue by framiere** [confluentinc/cp-ansible#5]
There's plenty of ways to make ansible faster, I recommend to look into https://github.com/AdopteUnOps/rancher-ansible/blob/master/ansible.cfg to have ideas to improve our current configuration.

**Comment by JumaX** [comment]
@framiere we've started to make changes regarding some of these enhancements.  In particular, we just pushed a new release which contains pipelining, which should speed things up considerably.

**Comment by JumaX** [comment]
@framiere going to close this out since I haven't heard back from you in some time.  If you have further suggestions please feel free to open a new issue.
