### ISSUE TITLE
Enable Jolokia on molecule tests that are expecting it

### ISSUE THREAD

**Issue by jeqo** [confluentinc/cp-ansible#532]
**Describe the issue**
As jolokia flag has change from `jolokia_enabled=true -> false`, molecule tests expecting jolokia to be available will fail. Found in #531. I suspect other tests will have the same issue.

**To Reproduce**
Run `molecule verify -s mtls-debian`

**Comment by domenicbove** [comment]
We've checked all the molecule tests passed with the 610 release, this can be closed
