### ISSUE TITLE
Supporting mmap limit

### ISSUE THREAD

**Issue by chromy96** [confluentinc/cp-ansible#536]
Hi,

Reading through the Confluent's [production deployment docs](https://docs.confluent.io/platform/current/kafka/deployment.html#file-descriptors-and-mmap), I noticed that cp-ansible is not setting the mmap limit in the provisioned cluster.

The kafka broker role does set some VM subsystem properties as part of role's [default vars](https://github.com/confluentinc/cp-ansible/blob/6.0.1-post/roles/confluent.kafka_broker/defaults/main.yml#L35-L38).

My question is whether the mmap limit was omitted on purpose and if so, what was the reason?

**Comment by JumaX** [comment]
Hi @chromy96, thanks for the question.  This is a really good catch.  

It was not omitted on purpose from CP-Ansible, most likely the documentation was updated after the last update to CP-Ansible's OS parameters and thus has not been added.

This is something we can definitely add in short order.  Will create a PR for this in the next day or so and ask you to review.

Thanks again for finding this.

**Comment by erikgb** [comment]
Resolved by https://github.com/confluentinc/cp-ansible/pull/620
