### ISSUE TITLE
Jenkins build status not available (404)

### ISSUE THREAD

**Issue by gianluca-mascolo** [confluentinc/cp-ansible#551]
**Describe the issue**
Jenkins build state is not available to public contributors

**To Reproduce**
When I submit a PR, if I try to open the jenkins link ([example](https://jenkins.confluent.io/job/confluentinc-pr/job/cp-ansible/job/PR-549/17/display/redirect) ) I get
```
HTTP ERROR 404

Problem accessing /job/confluentinc-pr/job/cp-ansible/job/PR-549/17/display/redirect. Reason:

    Not Found
```
**Expected behaviour**
Jenkins build status should be available to give feedback to contributors. Example: [Confluentinc Contributors](https://jenkins.confluent.io/job/Confluentinc%20Contributors/) is public

**Comment by domenicbove** [comment]
@andrewegel Is there any way to help community contributors view Jenkins logs? I understand the VPN is involved, but oddly enough I can view the logs without being on VPN. I cannot start jobs without getting on the VPN

**Comment by erikgb** [comment]
@andrewegel As a contributor, is there any chance to get access to view the Jenkins CI logs? It is quite hard to contribute effectively without it! I am working in an environment where security policies block me from running the molecule tests locally (https://github.com/confluentinc/cp-ansible/blob/6.1.1-post/HOW_TO_TEST.md). Working "blindfolded" is very hard, and I do not want to waste maintainers time neither - on being CI-log proxies....

**Comment by erikgb** [comment]
Hooray! 🍾 This issue seems to have been fixed now! It seems like the link will only work on "recent" PRs. Closing issue.

@gianluca-mascolo Feel free to open if it doesn't work (for you).

**Comment by andrewegel** [comment]
Please don't @-me about issues like this @domenicbove - You need to raise them with the Confluent Tools Team.

**Comment by erikgb** [comment]
We might have closed this issue a bit too early - as it is still not working. The build log on https://github.com/confluentinc/cp-ansible/pull/627 is not working for me, I still get HTTP 404: https://jenkins.confluent.io/job/confluentinc-pr/job/cp-ansible/job/PR-627/5/display/redirect

**Comment by andrewegel** [comment]
Your PR's job can be found here: https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/cp-ansible/job/PR-627/

We have disabled the separate `confluentinc-pr` jenkins Org from building cp-ansible, so this issue is addressed, may take a week or so before the links will start showing up correctly.
