### ISSUE TITLE
Include a dedicated controller listener by default

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/cp-ansible#555]
[Here](https://github.com/confluentinc/cp-ansible/blob/6.1.0-post/roles/confluent.variables/defaults/main.yml) shows the default playbook variables, which includes an INTERNAL listener (which is used for RBAC, I think) and a BROKER listener which is used for inter broker communication. We should also create a controller listener by default.

See KIP 291 and KIP 402 for reference about the importance of the `control.plane.listener.name` property

**Comment by domenicbove** [comment]
Closing because https://github.com/confluentinc/cp-ansible/pull/556 is merged
