### ISSUE TITLE
Playbook with RHEL8 support

### ISSUE THREAD

**Issue by corrantho** [confluentinc/cp-ansible#558]
Hello,

**Describe the issue**
RHEL7 is still referenced in https://github.com/confluentinc/cp-ansible/blob/6.1.0-post/roles/confluent.common/defaults/main.yml
However, RHEL8 is now supported as per https://docs.confluent.io/platform/current/installation/versions-interoperability.html

**Expected behaviour**
Playbook up-to-date with RHEL8 version. Or a another official playbook working with RHEL8.

In the meantime, should I create my own playbook replacing `/7` by `/8` in `main.yml` or do you recommend a better solution?

Thanks in advance,

**Comment by domenicbove** [comment]
@corrantho Nice catch! Fix is in the works

**Comment by domenicbove** [comment]
Merged PR, closing this!
