### ISSUE TITLE
Exposition of sensitive values in ansible outputs

### ISSUE THREAD

**Issue by gianluca-mascolo** [confluentinc/cp-ansible#567]
**Describe the issue**
During execution of the playbook there are parts like [this](https://github.com/confluentinc/cp-ansible/blob/0c925803404396d41face98fb881f38140d01747/roles/confluent.kafka_broker/tasks/main.yml#L210) where a secret is printed on output. A best practice for Ansible is to hide sensitive outputs with [`no_log: True`](https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-keep-secret-data-in-my-playbook)

**Expected behaviour**
Secrets and password must not be printed in output to protect them.

**Environment (please complete the following information):**
Any

**Comment by domenicbove** [comment]
Oh good idea, feel like those passwords should be masked no matter what, without even adding a no_log flag.

Are there any others that you've found? I think in rbac we log the mds super user'r username, not password

**Comment by gianluca-mascolo** [comment]
At a glance with a simple `grep` I found occurencies of the `shell` command that references sensitive vars in these files:
```
roles/confluent.ssl/tasks/export_certs_from_keystore_and_truststore.yml
roles/confluent.ssl/tasks/self_signed_certs.yml
roles/confluent.ksql/tasks/set_principal.yml
roles/confluent.kafka_broker/tasks/main.yml
roles/confluent.test.ldap/tasks/main.yml
roles/confluent.test.kerberos/tasks/redhat.yml
```
I don't know if Ansible has some mechanism to hide just passwords or some vars. All that I found was the `no_log` option.

**Comment by domenicbove** [comment]
PR merged, thanks for the contribution
