### ISSUE TITLE
Undefined variable in upgrade_kafka_broker_log_format.yml

### ISSUE THREAD

**Issue by erikgb** [confluentinc/cp-ansible#584]
**Describe the issue**
It seems like https://github.com/confluentinc/cp-ansible/commit/ad7de2102b49b157ec8853a220192b796eab452c introduced a bug in `upgrade_kafka_broker_log_format.yml` (undefined variable). With reference to the [Ansible upgrade documentation](https://docs.confluent.io/ansible/current/ansible-upgrade.html), I am trying to upgrade one of our clusters from version 6.0 to 6.1. We prefer to run everything in Ansible check mode before performing changes, and this is our current situation, but I do not think that matters in this case.

**To Reproduce**
```shell
cd /path/to/cp-ansible
git fetch
git checkout 6.1.0-post
```
Perform steps 1-5 in the upgrade procedure. Then to step step 6:
```shell
ansible-playbook -i /path/to/hosts.yml upgrade_kafka_broker_log_format.yml -e kafka_broker_upgrade_end_version=6.1
```

**Expected behaviour**
The playbook runs successfully with no errors

**Actual behaviour**
```log
TASK [set_fact] ****************************************************************
fatal: [<host>]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'upgrade_to_version' is undefined
  
    The error appears to be in '<path>/cp-ansible/6.1/upgrade_kafka_broker_log_format.yml': line 27, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - set_fact:
          ^ here
```

**Environment (please complete the following information):**
 - OS: RHEL 8 (hosts), Debian based Ansible controller container
 - CP-Ansible Branch: 6.1.0-post
 - Ansible Version: 2.10

@domenicbove I would be happy to submit a PR to fix this, but there are probably various ways to fix this issue. Please let me know what you think!

**Comment by domenicbove** [comment]
yep that looks like a bug, that we are using the wrong variable, should be:

```
        log_message_format_version: "{{'2.3' if kafka_broker_upgrade_end_version is match('5.3.*') else
          '2.4' if kafka_broker_upgrade_end_version is match('5.4.*') else
          '2.5' if kafka_broker_upgrade_end_version is match('5.5.*') else
          '2.6' if kafka_broker_upgrade_end_version is match('6.0.*') else
          '2.7' }}"
```
That code block must have been copied from the other upgrade playbook, WDYT?

**Comment by domenicbove** [comment]
Please try that out and open a PR into the 6.1.0-post branch. i'll review right away. Thanks for your help!

**Comment by erikgb** [comment]
> That code block must have been copied from the other upgrade playbook, WDYT?

@domenicbove Yes, it seems to have been copied from the `upgrade_kafka_broker.yml` playbook. You might want to review that sometime? Makes sense to have copy-paste "safe" code. 😄 Thanks for your prompt response!

**Comment by domenicbove** [comment]
I want to do a revamp of the upgrade scripts soon, moving much into tasks within the component roles, like you did with the create groups. Sorry they've been buggy!

**Comment by erikgb** [comment]
Yes, roles seems easier to reuse. The first part of an upgrade could potentially be part of the desired state? I.e. the component playbooks/roles. If I have understood it correctly, the post-upgrade playbook defines the point-of-no-return? You could eventually downgrade/rollback until the log format version is upgraded, right?

**Comment by domenicbove** [comment]
Yes you have it: updating the `log.message.format.version` kafka property can be problematic for your kafka clients!

Which makes the kafka upgrade like a 2 step process:
upgrade kafka but keep that property set at old version
upgrade that protocol version when you think your clients can handle it

I suppose a mechanism for rolling that protocol version back would be easy to implement in case of disaster.

All in all, Ive heard its important to have test kafka clusters and clients, mimicking prod, and to test these processes out!
