### ISSUE TITLE
Double entries in connect config

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#586]
**Describe the issue**
If using RBAC and setting at the same time the rest.extenstion for Replicator Monitoring the connect config will have twice a setting for `rest.extenstion` and fail..

**To Reproduce**
activate RBAC and setting kafka connect setting eg in the inventory file:

```
kafka_connect:
  properties:
    rest.extension.classes: "io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension"
```
the connect-distributed.properties file will contain two lines:

```
rest.extension.classes=io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension
rest.extension.classes=io.confluent.connect.security.ConnectSecurityExtension,io.confluent.connect.secretregistry.ConnectSecretRegistryExtension
```

the "faulty" line is probably this one:

https://github.com/confluentinc/cp-ansible/blob/5.5.3-post/roles/confluent.kafka_connect/templates/connect-distributed.properties.j2#L140

**Environment (please complete the following information):**
 - OS: [e.g. RHEL 7.6]
 - CP-Ansible Branch: [5.5.3-post]
 - Ansible Version [e.g. ansible 2.9.6]

I am aware that the mechanism is a different one for cp-6, is this issue for later versions "fixed"?
Would you accept a PR for 5.5.3?

**Comment by domenicbove** [comment]
Yes looks like a bug, please make bug fix PR into in 5.5.x branch

Nice catch!

**Comment by domenicbove** [comment]
Seeing as the custom properties feature works in 6.0.0, I would say we could use this limitation to get you to upgrade. Or simply make use of the `confluent_repo_version` and `confluent_package_version` variables. WDYT?

**Comment by rohit2b** [comment]
Since this is supported in the recent product versions of CP 6.0.0+, we don't plan to support this in CP 5.5.0. 

Closing this issue.
