### ISSUE TITLE
Incorrect License Property - CCloud Sample Inventory

### ISSUE THREAD

**Issue by feocco** [confluentinc/cp-ansible#600]
Incorrect Spelling of license value in Control Center configuration within `sample_inventories/ccloud.yml`:
* `confluent.licence` -> `confluent.license`
* [Link to Sample Inventory](https://github.com/confluentinc/cp-ansible/blob/e65d9021c98da3afabcb63c4cbc3e2062f811d90/sample_inventories/ccloud.yml#L113)

Incorrect spelling results in an invalid license exception(or using a trial license).

**Comment by domenicbove** [comment]
@feocco fix is in the .x branches now, will be in future `-post` branches
