### ISSUE TITLE
Force users to specify the protocol

### ISSUE THREAD

**Issue by jcustenborder** [confluentinc/cp-ansible#62]
I've been thinking about how to use this project to do rolling upgrades. I think it makes sense if we force have the user specify `inter.broker.protocol.version` and `log.message.format.version`. This would prevent an on the fly upgrade if someone does `yum upgrade`

**Comment by JumaX** [comment]
@jcustenborder we are actively investigating this now, and are looking at exactly such a mechanism whereby a user would have to specify a variable to change the protocol and format versions.

**Comment by jcustenborder** [comment]
I'm cool with that. Personally I just don't want a default value. The
problem we run into is upgrading the software. If I don't set a value and
accidently yum upgrade a box, I could get a new version of kafka which
changes the message format. Think about shared responsibility
organizations. Org A is responsible for Confluent, and org b is responsible
for Linux. Org b will be along every 2 weeks to run a yum upgrade. Because
of this I want to force this to be set. The next level would be force it to
be set and validate it in the ansible tier.

**Comment by JumaX** [comment]
@jcustenborder We have just released CP-Ansible 5.4.0 which now includes rolling upgrades and has a separate step for specifying the protocol.  Docs can be found here:
https://docs.confluent.io/current/installation/installing_cp/cp-ansible.html#upgrading-cp-5-3-x-to-version
