### ISSUE TITLE
zookeeper-server-start[21650]: java.io.IOException: Unable to create data directory

### ISSUE THREAD

**Issue by dzhyw** [confluentinc/cp-ansible#64]
Sep 29 09:35:47 confluent_node1 zookeeper-server-start[21650]: java.io.IOException: Unable to create data directory /usr/local/data/zookeeper/version-2

Feedback 2 questions：

1.Missing task to create a directory 

2.Missing installation jdk devel package 。such as  jps tools

**Comment by JumaX** [comment]
Closing due to no recent update.
