### ISSUE TITLE
KeyStore and TrustStore Passwords for Option #1

### ISSUE THREAD

**Issue by prestonmcgowan** [confluentinc/cp-ansible#641]
**Describe the issue**
The example for setting the keystore and truststore passwords in the hosts_example does not make it evident that a user can set the passwords when they choose `Option 1: Custom Certs`.

`Option 2: Custom Keystores and Truststores` calls out the following variables:
* `ssl_keystore_key_password: mystorepassword`
* `ssl_keystore_store_password: mystorepassword`
* `ssl_truststore_password: truststorepass`

May these also be used in Option 1? If so, can the documentation be reworked to show the passwords can be set with either option?

Link to hosts_example.yml: https://github.com/confluentinc/cp-ansible/blob/6.1.1-post/hosts_example.yml#L47

**Comment by prestonmcgowan** [comment]
Here are the list of values that need to be set.

I grabbed this list from cp-ansible/roles/confluent.variables/defaults/main.yml:
control_center_keystore_keypass:
control_center_keystore_storepass:
control_center_truststore_storepass:
kafka_broker_keystore_keypass:
kafka_broker_keystore_storepass:
kafka_broker_truststore_storepass:
kafka_connect_keystore_keypass:
kafka_connect_keystore_storepass:
kafka_connect_replicator_consumer_keystore_keypass:
kafka_connect_replicator_consumer_keystore_storepass:
kafka_connect_replicator_consumer_truststore_storepass:
kafka_connect_replicator_keystore_keypass:
kafka_connect_replicator_keystore_storepass:
kafka_connect_replicator_monitoring_interceptor_keystore_keypass:
kafka_connect_replicator_monitoring_interceptor_keystore_storepass:
kafka_connect_replicator_monitoring_interceptor_truststore_storepass:
kafka_connect_replicator_producer_keystore_keypass:
kafka_connect_replicator_producer_keystore_storepass:
kafka_connect_replicator_producer_truststore_storepass:
kafka_connect_replicator_truststore_storepass:
kafka_connect_truststore_storepass:
kafka_rest_keystore_keypass:
kafka_rest_keystore_storepass:
kafka_rest_truststore_storepass:
ksql_keystore_keypass:
ksql_keystore_storepass:
ksql_truststore_storepass:
schema_registry_keystore_keypass:
schema_registry_keystore_storepass:
schema_registry_truststore_storepass:
zookeeper_keystore_keypass:
zookeeper_keystore_storepass:
zookeeper_truststore_storepass:

**Comment by DennisFederico** [comment]
Faced this... created PR https://github.com/confluentinc/cp-ansible/pull/1078

**Comment by utkarsh5474** [comment]
Closing in favour of https://github.com/confluentinc/cp-ansible/pull/1083. Thanks @DennisFederico 
This change is now available in the latest patch.
