### ISSUE TITLE
Query : What is the best way to create new set of client credentials for a setup

### ISSUE THREAD

**Issue by quotient-vthakur** [confluentinc/cp-ansible#656]
Hi,

I would like to create new set of client credentials. In our ORG we have on CP kafka platform that will serve several teams. Each team will have individual producers and consumers (essentially clients). We would like to isolate each team with its own set of cred. We already have enabled sasl_protocol: plain. I see in here https://github.com/confluentinc/cp-ansible/blob/6.1.1-post/roles/confluent.variables/defaults/main.yml we have only one default set for sasl_plain_users.client. Can i add multiple stanzas in same place so that it will generate the config which i can share? E.g. `sasl_scram_users: "{
  'admin': {
    'principal': 'admin',
    'password': 'admin-secret'
  },
  'client': {
    'principal': 'client',
    'password': 'client-secret'
  },
  'client1': {
    'principal': 'some1',
    'password': 'some1password'
  }`

**Comment by domenicbove** [comment]
Yes, you simply need to put a dict in your inventory file that gets merged into our users dictionary. See our docs:
https://docs.confluent.io/ansible/current/ansible-authenticate.html#configure-sasl-plain-authentication

**Comment by domenicbove** [comment]
LMK if you have more questions!
