### ISSUE TITLE
Questions about community version cp-ansible

### ISSUE THREAD

**Issue by ChenZhaobin** [confluentinc/cp-ansible#660]
Qustion1: How to clean  hosts deployed by cp-ansible? 
After I run the command :"
yum remove $(yum list installed | grep 'confluent' | awk  '{ print $1}')
",the data in kafka still exists,and some services still running  such as control center .
Qustion2: How to  down grade  enterprise version to community version
Question3 : what will happen if I deployed using enterprise version ,and time expired ,will everything works fine except control-center?
Question4: what the differents between opensource kafka and community version of confluent-kafka? Are they using the same source code or not?

**Comment by ChenZhaobin** [comment]
For the first question, I solved it by running below command:
```
yum remove $(yum list installed | grep 'confluent' | awk '{ print $1}')  &&  \

rm -rf /var/lib/confluent&& \
rm -rf /var/lib/kafka&& \
rm -rf /var/lib/kafka-streams &&  \
rm -rf /var/lib/zookeeper &&  \



rm -rf /etc/kafka&& \
rm -rf /etc/kafka-rest &&  \
rm -rf /etc/confluent-control-center && \
rm -rf /etc/confluent-metadata-service&&  \
rm -rf /etc/confluent-rebalancer &&  \

rm -rf /var/log/confluent/&& rm -rf /var/log/kafka/ &&  \

rm -rf /etc/systemd/system/confluent-zookeeper.service.d && \
rm -rf /etc/systemd/system/confluent-kafka.service.d && \
rm -rf /etc/systemd/system/confluent-kafka-rest.service.d && \
rm -rf /etc/systemd/system/confluent-server.service.d && \
rm -rf /etc/systemd/system/confluent-schema-registry.service.d && \
rm -rf /etc/systemd/system/confluent-kafka-connect.service && \
rm -rf /etc/systemd/system/confluent-control-center.service.d && \
rm -rf   /usr/lib/systemd/system/confluent-zookeeper.service &&  \
rm -rf   /usr/lib/systemd/system/confluent-kafka.service && \
rm -rf   /usr/lib/systemd/system/confluent-kafka-rest.service && \
rm -rf   /usr/lib/systemd/system/confluent-server.service &&\
rm -rf  /usr/lib/systemd/system/confluent-schema-registry.service.d&&\
rm -rf /usr/lib/systemd/system/confluent-kafka-connect.service.d&&\
rm -rf   /usr/lib/systemd/system/confluent-control-center.service
```

**Comment by JumaX** [comment]
Hello @ChaoqunCHEN to answer your questions:

2. You can choose which version of Confluent platform you wish to install via the inventory file as outlined here: https://github.com/confluentinc/cp-ansible/blob/6.1.1-post/hosts_example.yml#L113
3. If the 30 day trial expires, then various components will fail to work, including the brokers, as Confluent-Server contains a lot of extra features that are not available in Confluent-Kafka.
4. Confluent Server builds on top of Confluent Kafka (Full Open source) to add additional features which require a license.  It's an OpenCore model.  

You can find more details here: https://docs.confluent.io/platform/current/platform.html#cp-vs-ak-key-differences

Thanks for the questions!
