### ISSUE TITLE
Should be able to customize which properties are encrypted with confluent platform secrets

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/cp-ansible#663]
**Describe the issue**
I can't find any way to add custom properties to be encrypted with secrets protection. Only properties with "password" are encrypted by default, but there are other sensitive properties like ldap credentials and basic auth credentials that don't contain the word "password". 

Ideally the secret protection tool itself would have a more opinionated default than just searching for the word "password", but ansible should still offer the capability to choose which properties to encrypt.

**Comment by JumaX** [comment]
@chuck-confluent historically it hasn't been possible to encrypt any desired property, it was only available to passwords etc, thus why the current limitation in CP-Ansible.  It looks we have had added additional capabilities in newer releases where it is now possible to encrypt specific properties, as per docs here: https://docs.confluent.io/platform/current/security/secrets-tutorial.html

We can look into this for a future release.

**Comment by rohit2b** [comment]
Hi @chuck-confluent - would this help? https://docs.confluent.io/ansible/current/ansible-configure.html#configure-secrets-protection. In there is instructions on how to add properties to encrypt.

**Comment by chuck-confluent** [comment]
@rohit2b Yes that's exactly what I'm looking for!

It looks like the task is here https://github.com/confluentinc/cp-ansible/blob/master/roles/confluent.common/tasks/secrets_protection.yml#L63, where it's referencing a variable simply called "properties". Example of how it's implemented for the broker: https://github.com/confluentinc/cp-ansible/blob/master/roles/confluent.kafka_broker/tasks/main.yml#L175. 

Thanks!
