### ISSUE TITLE
rbac-mtls-provided-ubuntu scenario uses centOS, not ubuntu

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/cp-ansible#679]
https://github.com/confluentinc/cp-ansible/blob/6.1.1-post/roles/confluent.test/molecule/rbac-mtls-provided-ubuntu/molecule.yml

This molecule scenario appears to use CentOS hosts, not ubuntu. should it be renamed rbac-mtls-provided-rhel?

**Comment by domenicbove** [comment]
Only the ldap server is on centos, the other containers are on ubuntu: https://github.com/confluentinc/cp-ansible/blob/6.1.1-post/roles/confluent.test/molecule/rbac-mtls-provided-ubuntu/molecule.yml#L93

**Comment by chuck-confluent** [comment]
Oops, my bad! Too many tabs open on different scenarios. Thanks Domenic
