### ISSUE TITLE
Wrong statement in hosts_example for zookeeper_ssl

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#685]
**Describe the issue**
The host_example file states clearly that `zookeeper_ssl_enabled` is by default switched off, even if the general `ssl_enabled` setting is on `true`.
https://github.com/confluentinc/cp-ansible/blob/6.2.0-post/hosts_example.yml#L71
That is however not anymore true.
https://github.com/confluentinc/cp-ansible/blob/6.2.0-post/VARIABLES.md#zookeeper_ssl_enabled

When not using zookeeper ssl and not setting explictly `zookeeper_ssl_enabled: false` you might run into an error when doing the ZK Healthcheck with superfluous `-Dzookeeper.ssl` settings.

**Comment by domenicbove** [comment]
I just updated it: https://github.com/confluentinc/cp-ansible/blob/6.2.0-post/hosts_example.yml#L73

I would not trust everything in that file though, we are rethinking it.
