### ISSUE TITLE
kafka-consumer-groups with SASL_SSL

### ISSUE THREAD

**Issue by martenlindblad** [confluentinc/cp-ansible#69]
I try to edit the offset of certain consumer groups with the kafka-consumer-group tool
This is how I run the program: `KAFKA_HEAP_OPTS="-Xmx2G" kafka-consumer-groups --bootstrap-server 172.31.31.132:9092 --list --command-config client.properties`
Output:
```
[2018-11-08 13:51:23,607] ERROR [NetworkClient clientId=admin-1] Connection to node -1 failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
Error: Executing consumer group command failed due to SSL handshake failed
```
Client.properties content:
```
sasl.mechanism=PLAIN
# Configure SASL_SSL if SSL encryption is enabled, otherwise configure SASL_PLAINTEXT
security.protocol=SASL_SSL
ssl.ca.location=/var/ssl/private/snakeoil-ca-1.crt
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="client" \
  password="client-secret";
```
This is from our test deployment using the provided ansible playbook for deployment, hence the default values. 
How should I run the kafka-consumer-group with SASL_SSL enabled?

**Comment by cotedm** [comment]
It looks like you are missing a bunch of the required SSL properties:
https://docs.confluent.io/current/kafka/encryption.html#clients

There is a tools role that you can use to create the properties file for you as well:
https://github.com/confluentinc/cp-ansible/tree/5.0.x/roles/confluent.tools

Please let me know if that's helpful.

**Comment by martenlindblad** [comment]
Confirmed I was missing the confluent.tools task. The reason for that was that I was starting with the plaintext file all.yml which is lacking that task.
