### ISSUE TITLE
Depcrecating "datadir" variable

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#690]
The hosts_example suggest to set under `kafka_broker_custom_properties` all settings that should end up in the broker settings file.

However it is suggested to create 
```
kafka_broker:
  vars:
    datadir:
      - dir1
      - dir2
```

`datadir` will then be mapped onto `log.dirs`

In my attempt to be consistent and smart :D - I wrote this:

```
kafka_broker_custom_properties:
  datadir:
    - dir1
    - dir2
```

which lead to Kafka using the default value for `log.dirs`.

Imho it would be more consistent to deprecate the `datadir` variable and instead document in the hosts_example the "standard" way of setting properties of the kafka broker.

```
kafka_broker_custom_properties:
  log.dirs:
    - dir1
    - dir2
```

**Comment by domenicbove** [comment]
We should deprecate the hosts_example.yml, its outdated. But this is a good one to track!

**Comment by domenicbove** [comment]
Also, the kafka_broker_custom_properties dict should be used the way you set properties in server.properties. So this is currently valid:
```
kafka_broker_custom_properties:
  log.dirs: dir1,dir2
```
not the list object

**Comment by JumaX** [comment]
This has now been resolved.
