### ISSUE TITLE
Configure Kafka broker to use Zookeeper chroot path

### ISSUE THREAD

**Issue by a-narenji** [confluentinc/cp-ansible#691]
We need to configure Kafka brokers to use Zookeeper chroot path. By default, Kafka creates znodes in root of Zookeeper.
In order to separate app and Kafka configurations, it is necessary to set different chroot path for Kafka.

Is it possible to have Kafka with chroot Zookeeper path provisioned by cp-ansible?

As an example. we need cp-ansible to configure _zookeeper.connect_ to have a value like: **hostname1:port1,hostname2:port2,hostname3:port3/chroot/path**.

**Comment by a-narenji** [comment]
@JumaX Many thanks for your reply.
We are not using existing Zookeeper cluster, and we use the same Zookeeper which cp-ansible set it up for us.
Our develop team may need to use Zookeeper for another purpose, and it may not be reasonable to have a second Zookeeper cluster dedicated to develop team requirements.

So, it would be helpful that cp-ansible let us to have chroot path in _zookeeper.connect_ property.
Additionally, since we need to enable SASL, it is not enough to change _zookeeper.connect_ only, but also, it is required to change [Create SCRAM Users](https://github.com/confluentinc/cp-ansible/blob/2627863faea975c917b2da17d996ed3048d95826/roles/confluent.kafka_broker/tasks/main.yml#L271) and [Create SCRAM 256 Users](https://github.com/confluentinc/cp-ansible/blob/2627863faea975c917b2da17d996ed3048d95826/roles/confluent.kafka_broker/tasks/main.yml#L283) tasks in such a way that cp-ansible be able to create SCRAM users to use Zookeeper chroot path.

**Comment by JumaX** [comment]
@a-narenji Thanks for the additional details.  Unfortunately, at this time we do not support this configuration.  Specifically around the scram users. Of additional note, is that Zookeeper is being removed as a kafka dependency soon, so we will review this and see if it makes sense to allow this modification with zookeeper for a future release.

**Comment by domenicbove** [comment]
@a-narenji Can you please review: https://github.com/confluentinc/cp-ansible/pull/694

**Comment by a-narenji** [comment]
We checked it in our test environment.
It worked great.
Many thanks for adding this feature.
