### ISSUE TITLE
Add git tag and commit sha to deployed property files

### ISSUE THREAD

**Issue by prestonmcgowan** [confluentinc/cp-ansible#697]
**Describe the issue**
When I pulled down the CP-Ansible I was pulling from a specific git branch and commit.
Sadly, the Ansible Control Node was lost and we need to rebuild it.
We saved off our inventory file but did not save off the CP-Ansible project to our internal git.
When we went to recover our configuration we were unable to identify which version of CP-Ansible we had deployed previously.

**To Reproduce**
Perfect storm of "I'll do it later", and "who needs this system <delete>".

**Inventory File**

The following is included in the property files generated by CP-Ansible
`# Maintained by Ansible`

I would like to add to that header comment the git branch and git commit id from the CP-Ansible (current directory) project.

Sample
```
# Maintained by Ansible
# Project Details: Origin (https://github.com/confluentinc/cp-ansible) Branch (6.2.0-post) Commit SHA (2627863f)
```

Git Commands to built the sample:
Origin `git config --get remote.origin.url`
Branch `git rev-parse --abbrev-ref HEAD`
Commit SHA `git rev-parse --short HEAD`

**Comment by utkarsh5474** [comment]
We can do this, but we won't be taking it up rn this way. 
In our later branches, we have this variable - https://github.com/confluentinc/cp-ansible/blob/7.2.2-post/docs/VARIABLES.md#kafka_broker_telemetry_ansible_labels_enabled which if set to true, will drop a property called `confluent.telemetry.labels.confluent.ansible.playbooks.version: "{{confluent_ansible_branch}}"` in the server.properties file of the broker. So, this can be used.
Besides that, the commit SHA of the released branches will be static until we see a hotfix go in. With latest certification related changes, the collection is also available on ansible galaxy, automation hub.
