### ISSUE TITLE
Kafka Connect Distributed can't communicate with broker

### ISSUE THREAD

**Issue by martenlindblad** [confluentinc/cp-ansible#70]
We run Confluent 5.0.1 from cp-ansible with three nodes configured with connect-distribued.
Since yesterday we got problems with connect.

When I push a new connection:
```
{
    "name": "signal-elastic-sink",
    "config": {
        "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
        "tasks.max": "6",
        "topics": "signal-source",
        "topic.index.map": "signal-source:signal",
        "schema.ignore": "false",
        "connection.url": "http://elastic01:9200",
        "key.ignore": "true",
        "type.name": "signal",
        "name": "signal-elastic-sink"
    }
}
```

Syslog get a frenzy with the following:
`Nov  9 07:24:25 BROKER02 connect-distributed[16386]: [2018-11-09 07:24:25,451] ERROR [│worker rebalance)"}% Producer clientId=confluent.monitoring.interceptor.consumer-4] Connection to node -1 failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient:663)  `

**Comment by cotedm** [comment]
Looks like you have something going wrong with your worker configuration. Like the monitoring interceptor is failing to authenticate with SSL. These parameters should be handling this for you, so I suspect you have done something else with the worker properties files for connect https://github.com/confluentinc/cp-ansible/blob/5.0.x/roles/confluent.connect-distributed/templates/connect-distributed_sasl_ssl.properties.j2#L30-L34

Can you validate or post your worker properties file?

**Comment by cricket007** [comment]
> Producer clientId=confluent.monitoring.interceptor.consumer

This seems to be an error with the interceptors, not Connect

**Comment by JumaX** [comment]
I can confirm that we do not currently configure the interceptors.  We have this on the roadmap for a future release.
