### ISSUE TITLE
Using headless JDK on Redhat?

### ISSUE THREAD

**Issue by jwcranford** [confluentinc/cp-ansible#73]
Any reason why the headless JDK package isn't used on Redhat?  Specifically, has anyone tested the java-1.8.0-openjdk-headless package instead of java-1.8.0-openjdk?

**Comment by JumaX** [comment]
@jwcranford We do not recommend headless as per the official confluent docs.  To be frank, I am not sure it's ever been tested.

**Comment by jwcranford** [comment]
That’s good to know. Seems to work ok for my company, but I didn’t realize it’s not a recommended configuration. 

- Jonathan

**Comment by jwcranford** [comment]
I've tested it successfully and it works just fine. If anyone's interested in details, I can provide. I'll close this issue for now.
