### ISSUE TITLE
kafka_server_jaas.conf missing on zookeeper digest

### ISSUE THREAD

**Issue by juresaht2** [confluentinc/cp-ansible#733]
**Describe the issue**
With settings:
```
zookeeper_quorum_authentication_type: digest
zookeeper_client_authentication_type: digest
```

The file `/etc/kafka/kafka_server_jaas.conf` is not generated. As a result the step "Create SCRAM 256 Users" fails.

A workaround is to also configure:
```
zookeeper_sasl_protocol: digest
```

However this setting is deprecated.

This is probably at fault, since it only considers the case for kerberos and not digest.
https://github.com/confluentinc/cp-ansible/blob/6.2.0-post/roles/confluent.variables/defaults/main.yml#L220

**Environment (please complete the following information):**
 - OS: CentOS 8
 - CP-Ansible Branch: 5.5.0-post
 - Ansible Version [e.g. ansible 2.10.6

**Comment by utkarsh5474** [comment]
Closing this since fixed by #1019.
