### ISSUE TITLE
When creating broker datadir directories, you cannot specify multiple datadirs

### ISSUE THREAD

**Issue by liko9** [confluentinc/cp-ansible#74]
If I override the datadir to be /dir01,/dir02,/dir03, the parameter logs.dir is correct in server.properties - but it also tries to create the directories with a mkdir command which fails because it takes it as "mkdir /dir01,/dir02,/dir03" instead of 3 separate mkdir commands "mkdir /dir01; mkdir /dir02; mkdir /dir03"

**Comment by cricket007** [comment]
I believe the data directories need to be an array, not comma-separated. 

https://github.com/confluentinc/cp-ansible/blob/5.0.x/roles/confluent.kafka-broker/tasks/main.yml#L17

**Comment by domenicbove** [comment]
Agreed, the code expects an array
