### ISSUE TITLE
confluent repositories out of sync with version tags

### ISSUE THREAD

**Issue by kpweiler** [confluentinc/cp-ansible#75]
Hi there. On version tag "v5.1.0", the confluent.common role installs 5.0 repos instead of 5.1.

I would fix this with a pull request, but I'm not sure which branch you would want it on.

**Comment by kpweiler** [comment]
https://github.com/confluentinc/cp-ansible/pull/76

**Comment by cotedm** [comment]
Thanks! I merged and updated the tag. Thank you for contributing!
