### ISSUE TITLE
Unable to upgrade connect plugins

### ISSUE THREAD

**Issue by Verticaleap** [confluentinc/cp-ansible#757]
**Describe the issue**
We found that we are unable to upgrade already installed kafka connect plugins to newer versions using this playbook. 

**To Reproduce**
Run playbook with var kafka_connect_confluent_hub_plugins including a plugin, then rerun the playbook with the plugin set to a different version. The playbook will not update the version. Based on the logic in the playbook, this should be reproducible with any plugin as long as the name of the plugin does not change.

**Expected behavior**
I would expect that changing a plugin's version in our hosts.yml, and then rerunning all.yml, would cause the plugin to be upgraded to the new version specified.

**Environment**
 - OS: RHEL 7.8
 - CP-Ansible Branch: 6.2.0-post
 - Ansible Version: 2.9.6

I believe the issue stems from this line here:

https://github.com/confluentinc/cp-ansible/blob/8daf3140882ddbe84cecf0320c52592374a1a66e/roles/confluent.kafka_connect/tasks/confluent_hub.yml#L9

Because ansible is only checking for if the plugin folder exists, it is not checking the currently installed version has changed. I believe a better when statement would be to check the manifest.json within the plugin dir, and compare the version specified there to the version specified in the inventory file.

**Comment by JumaX** [comment]
@Verticaleap This is a really great idea, and something we will consider for a future release.  We also always welcome PR's from the community, if you have any cycles to contribute. Really appreciate the feedback on this.

**Comment by wadhwa1** [comment]
We can upgrade kafka connect plugins (**installed via confluent hub** _kafka_connect_confluent_hub_plugins_) to newer versions by replaying the playbook. 
confluent-hub install takes care of uninstalling any previous version of plugin, and upgrading to new one.
Fix should be available in upcoming patch release - `6.2.8-post` (ETA- 12th dec)
And is already available in 7.3.x (`7.3.1-post`)
Thanks!
