### ISSUE TITLE
Add tests that use LdapAuthenticateCallbackHandler for authentication via LDAP

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/cp-ansible#764]
The education team has found that it's a very common use case to handle authentication over LDAP via the `LdapAuthenticateCallbackHandler`.

This is especially true with RBAC configurations, since LDAP is already needed to provide principals anyway.

It would be good to have test scenarios that use the `LdapAuthenticateCallbackHandler` for AuthN and RBAC for AuthZ. I have working configs from various courses in the curriculum library if reference is needed.

**Comment by chuck-confluent** [comment]
Working inventory: https://github.com/confluentinc/training-adm-auto-ansible/tree/master/infra/course-src/inventories/production

See also module 5 of the ansible education course, "Deploy Confluent Securely with Ansible", complete with hands-on lab.

**Comment by mansisinha** [comment]
Hi @chuck-confluent , thanks for pointing this out. I've added a test to cover this in this [PR](https://github.com/confluentinc/cp-ansible/pull/1210). Please review once, I will then merge it.

**Comment by chuck-confluent** [comment]
Hey @mansisinha , thanks so much for the PR!

Perhaps we should request a reviewer from the ansible team, like @domenicbove ? Or, maybe check on the #ansibe-oncall slack channel?

**Comment by mansisinha** [comment]
closing the issue since the test has been merged in 7.3
