### ISSUE TITLE
RPM install is broken on RHEL 7

### ISSUE THREAD

**Issue by erikgb** [confluentinc/cp-ansible#773]
**Describe the issue**
The default value for the variable `confluent_common_repository_redhat_dist_baseurl` was changed in https://github.com/confluentinc/cp-ansible/pull/707/files to a value that does not work on RHEL 7 - at least not on our systems. On RHEL 7, the yum-variable `releasever` resolves to `7Server`, with does not fit into the path to the Confluent RPM repository. On RHEL 8, the yum variable resolves to `8`, which should work.

**To Reproduce**
Try to install cp-ansible on a RHEL7 system; obeserve that the RPMs are not found.

**Expected behaviour**
Should install/upgrade Confluent components.

**Inventory File**
Please provide your inventory file in order to aid in the investigation.

**Environment (please complete the following information):**
 - OS: RHEL 7
 - CP-Ansible Branch: 6.2.1-post
 - Ansible Version: 4 (latest)

**Comment by erikgb** [comment]
@andrewegel Sorry for @'ing you, but the Red Hat sysadmins in my organization tells me that it is common to symlink `7Server` (and `7Client`) to `7` in upstream RPM-repos - as a workaround for issues like this one. Is that something that can be done in the Confluent RPM-repos? Ref. https://packages.confluent.io/rpm/6.2/

CC: @JumaX

**Comment by panasenco** [comment]
Experiencing the exact same issue here.

**Comment by DirectorrQ** [comment]
Experiencing the same issue with version 6 and upwards when trying to install on Amazon linux 2 using ansible version 2.9. Keep on getting the error below:
fatal: [ec2-35-87-177-23.us-west-2.compute.amazonaws.com]: FAILED! => {"changed": false, "msg": "https://packages.confluent.io/rpm/6.2/2/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found\nTrying other mirror.\n\n\n One of the configured repositories failed (Confluent repository (dist)),\n and yum doesn't have enough cached data to continue. At this point the only\n safe thing yum can do is fail. There are a few ways to work \"fix\" this:\n\n     1. Contact the upstream for the repository and get them to fix the problem.\n\n     2. Reconfigure the baseurl/etc. for the repository, to point to a working\n        upstream. This is most often useful if you are using a newer\n        distribution release than is supported by the repository (and the\n        packages for the previous distribution release still work).\n\n     3. Run the command with the repository temporarily disabled\n            yum --disablerepo=Confluent.dist ...\n\n     4. Disable the repository permanently, so yum won't use it by default. Yum\n        will then just ignore the repository until you permanently enable it\n        again or use --enablerepo for temporary usage:\n\n            yum-config-manager --disable Confluent.dist\n        or\n            subscription-manager repos --disable=Confluent.dist\n\n     5. Configure the failing repository to be skipped, if it is unavailable.\n        Note that yum will try to contact the repo. when it runs most commands,\n        so will have to try and fail each time (and thus. yum will be be much\n        slower). If it is a very temporary problem though, this is often a nice\n        compromise:\n\n            yum-config-manager --save --setopt=Confluent.dist.skip_if_unavailable=true\n\nfailure: repodata/repomd.xml from Confluent.dist: [Errno 256] No more mirrors to try.\nhttps://packages.confluent.io/rpm/6.2/2/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found\n", "rc": 1, "results": []}

**Comment by erikgb** [comment]
> Experiencing the same issue with version 6 and **upwards**

@DirectorrQ, do you mean RHEL version or CP version?

**Comment by DirectorrQ** [comment]
> > Experiencing the same issue with version 6 and **upwards**
> 
> @DirectorrQ, do you mean RHEL version or CP version?

The CP version.

**Comment by andrewegel** [comment]
> Experiencing the same issue with version 6 and upwards when trying to install on Amazon linux 2

CP and cp-ansible don't support Amazon Linux - Thats why the `$releasever` variable is being expanded to 2 - you could override this to 7 (since thats what AL2 is closest too in terms of ABI).

**Comment by andrewegel** [comment]
> the Red Hat sysadmins in my organization tells me that it is common to symlink 7Server (and 7Client) to 7 in upstream RPM-repos - as a workaround for issues like this one

@erikgb this is really only meant for CP 7.0 and above, but it can be used to get around your issue:

https://docs.confluent.io/platform/current/installation/installing_cp/rhel-centos.html

Where I've basically done exactly what you're asking for at https://packages.confluent.io/clients/rpm/centos/ where 7Server 7Client are "symliked" (Its a Cloud Front backed by S3) to 7. 

Since librdkafka packages are on the deprecation path behind the `rpm/${MAJOR_VERSION}` paths (Switch to the "global" /clients paths), I'm not inclined to add this as a feature for existing prior releases.

**Comment by nsharma-git** [comment]
Based on the above discussion, I"m closing this issue. Please reopen if you differ. 
To summarise - 
1. Amazon Linux is not supported by CP till date ( cp release 7.0.0 )
1. CP 7.0.x onwards 7server and 7client will be mapped to 7 in our repo. There isn't any plan to do the same for older releases.

**Comment by erikgb** [comment]
Thanks for the feedback, @andrewegel! This sounds ok to us. We are in the process of migrating to RHEL8 anyway, and are also tempted to upgrade to CP 7. Just awaiting some Openshift image fixes before heading for CP 7.
