### ISSUE TITLE
Zookeeper Get Leader/Follower task fails when ssl.clientAuth DNE in zookeeper-server.properties

### ISSUE THREAD

**Issue by hifly81** [confluentinc/cp-ansible#781]
**Describe the issue**
Zookeeper Get Leader/Follower task fails when ssl.clientAuth DNE in zookeeper-server.properties (no ssl enabled on zookeeper)

**To Reproduce**
zookeeper-server.properties with no SSL enabled

**Expected behaviour**
zookeeper_ssl_enabled var evaluated as false

**Logs**
 FAILED! => {"msg": "An unhandled exception occurred while templating '{{ binary_base_path }}/bin/kafka-run-class {% if zookeeper_ssl_enabled|bool %} -Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty -Dzookeeper.ssl.trustStore.location={{zookeeper_truststore_path}} -Dzookeeper.ssl.trustStore.password={{zookeeper_truststore_storepass}} -Dzookeeper.ssl.keyStore.location={{zookeeper_keystore_path}} -Dzookeeper.ssl.keyStore.password={{zookeeper_keystore_storepass}} -Dzookeeper.client.secure=true {% endif %} org.apache.zookeeper.client.FourLetterWordMain {{zookeeper_health_check_host | default(hostvars[inventory_hostname]|resolve_hostname) }} {{zookeeper_client_port}} srvr {% if zookeeper_ssl_enabled|bool %}true{% endif %}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ (slurped_properties.content|b64decode).split('\n') | select('match', '^ssl.clientAuth=need') | length > 0 }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ (slurped_properties.content|b64decode).split('\n') | select('match', '^ssl.clientAuth=need') | length > 0 }}): object of type 'generator' has no len()"}

**Environment (please complete the following information):**
 - OS: [e.g. RHEL 8.x]
 - CP-Ansible Branch: [6.2.1-post]
 - Ansible Version [e.g. ansible 2.9.15]

**Comment by spootrick** [comment]
The mentioned patch didn't seem to fix the issue.

**Comment by lavalex** [comment]
Same error here

**Comment by apellegr06** [comment]
Did someone find a solution ? Because I have the same error when upgrading from 5.5 to 7.0.1 with branch 6.2.1-post as mentioned in the documentation (https://docs.confluent.io/ansible/current/ansible-upgrade.html#ansible-upgrade-clone)

**Comment by apellegr06** [comment]
OK, the solution is to use the 6.2.2-post

**Comment by aalllop** [comment]
I'm using the correct versión of the playbook. I have downloaded using git clone https://github.com/confluentinc/cp-ansible \
  <path_to_cp-ansible>/ansible_collections/confluent/platform and then:

cd cp-ansible
git fetch
git checkout 7.1.0-post

**Comment by anuj-apdev** [comment]
Hi @aalllop ,
Can you please confirm that you are using ansible version `2.9.27` (which is the latest subversion of ansible 2.9) as it supports collections.
Can you also share the output of following command?
`ansible --version`
It seems like either the version you are using does not support collections.

**Comment by anuj-apdev** [comment]
Hi This issue looks specific to ansible version. I have tried to reproduce this with `ansible 2.9.27` and it is working fine.
I would suggest to upgrade to 2.9.27.
Feel free to reopen the issue if you are seeing this with ansible 2.9.27 also.

**Comment by ankitaramesh91** [comment]
I am still seeing this issue on ansible 2.9.27
