### ISSUE TITLE
stdout/stderr for the exact error", "rc": 1}

### ISSUE THREAD

**Issue by dsharma78** [confluentinc/cp-ansible#79]
Hi All,

I tried to install the Kafka confluent in redhat 7.4 but I am getting below error .

+ ansible-playbook -i ./ansible/cp-ansible-5.1.x/hosts.yml ./ansible/cp-ansible-5.1.x/all.yml

PLAY [preflight] ***************************************************************

TASK [Gathering Facts] *********************************************************
$ ssh-agent -k
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 13307 killed;
[ssh-agent] Stopped.
fatal: [127.58.7.166]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 127.58.7.166 closed.\r\n", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Please guide me to fx this issue .

Regards,
Deepak

**Comment by cricket007** [comment]
> sudo: a password is required

You will need to make sure ansible is connecting using an account with elevated privledges. 

https://docs.ansible.com/ansible/latest/user_guide/become.html

On the CLI, you could do `ansible-playbook -bK` to become a user and ask for that user's SSH password. Or you can provide a `--private-key-file`

**Comment by JumaX** [comment]
Looks like this is resolved by the above answer, closing.
