### ISSUE TITLE
Setting file descriptors allowed per process

### ISSUE THREAD

**Issue by michalklempa** [confluentinc/cp-ansible#80]
Given that Kafka should have maximum file descriptors opened set to high values (https://docs.confluent.io/current/kafka/deployment.html#file-descriptors-and-mmap), the Ansible roles should enable user to set the limits for nofile.

According to https://unix.stackexchange.com/a/345596 these limits may be set using systemd override file, which is already present in these roles:
```
[Service]
{% for key, value in kafka.connect.distributed.environment.items() %}
Environment="{{key}}={{value}}"
{% endfor %}
```
The format for NOFILE should be:
```
[Service]
{% for key, value in kafka.connect.distributed.environment.items() %}
Environment="{{key}}={{value}}"
{% endfor %}
LimitNOFILE=100000
```

**Comment by JumaX** [comment]
@michalklempa Thanks for the feedback.  We are addressing this in the next release which is due in the coming days.

**Comment by JumaX** [comment]
@michalklempa We have just merged the following PR which addresses this.

https://github.com/confluentinc/cp-ansible/pull/124
