### ISSUE TITLE
There should an option to let broker listen (bind) on specific IP address using listeners configuration option

### ISSUE THREAD

**Issue by michalklempa** [confluentinc/cp-ansible#87]
Currently, the `listeners` are set up in `roles/confluent.kafka-broker/templates/server.properties.j2` (and corresponding sasl_ssl and ssl versions) as:
```
# Maintained by Ansible
listeners=PLAINTEXT://:{{broker.config.port}}

{% include './includes/base_server.properties.j2' %}

# Confluent Support
{% include './includes/confluent_support.j2' %}
```
This leaves user of the role powerless in respect of setting the bind address of broker. In cloud environments, it is common that machines have two network interfaces : one for public internet access and one for VPC/internal network.

It would be great if role enabled user to set the listen host as IP address into these template files.

**Comment by mickaelgervais** [comment]
In our case, we have opened each port for each component corresponding on installed roles. We can improve roles we Ansible firewall module.
For example:
- hosts: connect-distributed
  become: true
  tasks:
  - include_vars: "../../roles/confluent.connect-distributed/defaults/main.yml"
  - name: Configure firewall (Kafka Connect ports)
    firewalld:
      port: "{{ kafka.connect.distributed.config['rest.port'] }}/tcp"
      state: enabled
      immediate: yes
      permanent: yes

**Comment by JumaX** [comment]
@michalklempa We have just merged the follow PR, which allows you to override this.

https://github.com/confluentinc/cp-ansible/pull/124
