### ISSUE TITLE
An unhandled exception occurred while templating '{{ zookeeper_combined_properties | combine(zookeeper_custom_properties) }}

### ISSUE THREAD

**Issue by qinxuan-chen** [confluentinc/cp-ansible#873]
hi support team,

i encounter one issue when trying to deploy confluent 7.0.1 with ansible playbook as below.
could you please give a hint where may the issue cause... thanks a lot~~
![2021-12-20_17-59-17](https://user-images.githubusercontent.com/78231298/146749054-8470a962-9ecb-4866-bf7f-441af3c87914.jpg)

my env:
centos 7
ansible [core 2.12.1]

thanks
regards,
Mark

**Comment by erikgb** [comment]
@qinxuan-chen From CP version 7.x cp-ansible is available as an Ansible collection. Did you follow the docs as described here? https://docs.confluent.io/ansible/current/ansible-download.html#download-ansible-for-ansible-2-11-or-higher-hosts

**Comment by qinxuan-chen** [comment]
hi @erikgb , 

thanks a lot~~ i follow the instruction via above link and manage to install ansible 7.0.1 collection.
after that, installation for confluent zookeeper is successful, but hit an error when trying to install confluent server. please refer to the screenshot below, it try to update broker log4j properties file and can not find the log4j properties file in /etc/kafka.... 
i try to do some trouble shooting , can find the script for zk to create log4j properties file in script roles/zookeeper/tasks/main.yml, but can not find the script where creaet log4j properties for broker..

could you please give a hint where may cause this issue?

![2021-12-21_04-36-25](https://user-images.githubusercontent.com/78231298/146829724-01f90f64-ff78-407d-934f-9ca829192d49.jpg)

thanks~~

regards
mark

**Comment by erikgb** [comment]
@qinxuan-chen I think a default `log4j.properties` is delivered as part of the kafka-broker package/archive. Please check the package/archive and/or search for `log4j.properties` on your host(s).

**Comment by qinxuan-chen** [comment]
thanks @erikgb , i got the root cause...

log4j.properties (with some other properties file) will be created into /etc/kafka when trying to deploy zookeeper node
(in my case, it is single node of zk & broker in same server , thus log4j.properties is in same folder /etc/kafka)

when i am trying to deploy zk, i hit an error of ansible version issue, so i continue to upgrade python/ansible, and rename folder /etc/kafka (this is key cause) to another name, and retry to deploy zk, but from 2nd try on wards, ansible will not create properties file for zk, other properties file e.g. log4j.properties will not be created any more..

after i uninstall zk and remove anything about confluent, and re-install zk/broker, it is good now.


thanks a lot for your help :-)

case closed

**Comment by erikgb** [comment]
@qinxuan-chen, glad I could help. Please note that co-located hosts (zookeeper and broker on the same host) is a hassle and not really supported. We have a few clusters doing this, but trying to work us out of that now. Just a friendly advice!

**Comment by qinxuan-chen** [comment]
currently stage i am just trying cp in testing purpose, not production. production architecture design will separate zk & broker in diff server. thanks a lot for your advice @erikgb  :-)
