### ISSUE TITLE
Yum Repo Add Task's proxy settings are wrong

### ISSUE THREAD

**Issue by nerdynick** [confluentinc/cp-ansible#891]
**Describe the issue**
The Yum Repo addition task in `roles/common/tasks/redhat.yml` uses `proxy.http_proxy` rather than `proxy.https_proxy`. Ideally this should probably use a fall back chain from https->http->none. In order to allow support when the https proxy is different than the http proxy in envs. 

Important to note, the confluent yum repos are TLS/SSL address, so a proxy supporting that type of traffic is needed.

**To Reproduce**
Steps to reproduce the behaviour:

1) Have 2 separate proxies configured in ansible for `http_proxy` and `https_proxy`
2) Ensure the `http_proxy` doesn't support TLS traffic. 
3) Attempt to run play for kafka_broker install
4) Note yum clean all and other yum commands will fail due to the unsupported traffic type.

**Comment by anuj-apdev** [comment]
@nerdynick The fix has been merged. You can verify this on Recent patches.
