### ISSUE TITLE
development environment - java memory update

### ISSUE THREAD

**Issue by allamiro** [confluentinc/cp-ansible#91]
Java memory is setup to use 1GB  though this can be ok for production however there are cases where you need to adjust this value (increase or decrease)  for kafka and zookeeper whether to improve the performance or for testing.

**Comment by dnewberger** [comment]
You should be able to change this value to meet your needs unless I'm missing something: https://github.com/confluentinc/cp-ansible/blob/5.1.x/roles/confluent.kafka-broker/defaults/main.yml#L15

**Comment by JumaX** [comment]
We are looking at exposing all core configurations in variable files in a future release to make it easier to adjust these settings from the root of the playbook.  Stay tuned.
