### ISSUE TITLE
confluent.metrics.reporter.ssl.endpoint.identification.algorithm does not exist

### ISSUE THREAD

**Issue by sknop** [confluentinc/cp-ansible#92]
roles/confluent.kafka-broker/defaults/main.yml sets the attribute
confluent.metrics.reporter.ssl.endpoint.identification.algorithm

but this property does not exist in the documentation and is probably superfluous. Should be removed to avoid confusion.

**Comment by JumaX** [comment]
@sknop It actually does exist in the documentation, and if you leave it blank, it disable hostname verification when using SSL.  We are actually in progress of removing this completely from the playbooks.  For your reference, the documentation is here: https://docs.confluent.io/current/security/security_tutorial.html#configuring-host-name-verification
