### ISSUE TITLE
ansible_ssh_user variable deprecated after Ansible version 2.0

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/cp-ansible#95]
In our `hosts.yml` file, we use a variable `ansible_ssh_user=centos`.

As of version 2.0 of Ansible, the variable has been renamed to `ansible_user`. https://ansible-tips-and-tricks.readthedocs.io/en/latest/ansible/inventory/

There should be a note in the documentation about certain assumptions we're making, like the machine running Ansible has username `centos`, or a step that says to change the user to the user where the playbook is being run from.

Let me know if I've misunderstood something!

**Comment by JumaX** [comment]
@chuck-confluent just filed a PR to correct his here:

https://github.com/confluentinc/cp-ansible/pull/149

I also think our docs are much better now for indicated what changes need to be made for the user.  Let me know your thoughts.

**Comment by chuck-confluent** [comment]
Looks good and the new docs are much improved! Thanks @JumaX
