### ISSUE TITLE
Getting "dict object' has no attribute 'datadir'" error while trying to install kafka broker using cp-ansible

### ISSUE THREAD

**Issue by rajeshhereforyou** [confluentinc/cp-ansible#97]
Hi,

I've Ansible 2.7.10 installed on my machine and trying to install kafka broker using 'cp-ansible' file and getting below error when running the task 'create broker data directories'

> 

TASK [confluent.kafka-broker : create broker data directories] *********************************************************************************************************************************************************************
fatal: [ip-x-x-x-x]: FAILED! => {"msg": "'dict object' has no attribute 'datadir'"}

Please suggest.

**Comment by rajeshhereforyou** [comment]
I'm able to make it work by changing the defaults/main.yml file of 'confluent.kafka-broker' role as below

> broker:
  config_file: /etc/kafka/server.properties
  systemd_file: /usr/lib/systemd/system/confluent-kafka.service
  systemd_override: /etc/systemd/system/confluent-kafka.service.d
  service_name: confluent-kafka
  datadir:
    - /var/lib/kafka/data
  systemd:
    enabled: yes
    state: started
  environment:
    KAFKA_HEAP_OPTS: "-Xmx1g"
  config:
    port: 9093
    group.initial.rebalance.delay.ms: 0
    log.retention.check.interval.ms: 300000
    log.retention.hours: 168
    log.segment.bytes: 1073741824
    num.io.threads: 16
    num.network.threads: 8
    num.partitions: 1
    num.recovery.threads.per.data.dir: 2
    offsets.topic.replication.factor: 3
    socket.receive.buffer.bytes: 102400
    socket.request.max.bytes: 104857600
    socket.send.buffer.bytes: 102400
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
    zookeeper.connection.timeout.ms: 6000
    metric.reporters: io.confluent.metrics.reporter.ConfluentMetricsReporter
#    confluent.metrics.reporter.bootstrap.servers: "{{inventory_hostname}}:{{broker.config.port}}"
#    confluent.metrics.reporter.topic.replicas: 3
#    ssl.endpoint.identification.algorithm: ""
#    confluent.metrics.reporter.ssl.endpoint.identification.algorithm: ""

**Comment by JumaX** [comment]
@rajeshhereforyou We published a new release, which is officially supported, on the 5.3.0 branch.  We have re-worked the playbooks considerably since your original post, and this issue is no longer present.  I would advise you to work with the 5.3.0 branch or later.
